### ISSUE TITLE
Usage of `subject_selection` key in the config file

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/ivadomed#1070]
## Issue description
The documentation concerning the usage of the ["subject_selection" key](https://ivadomed.org/configuration_file.html#subject-selection) seems unclear. There are 3 sub-keys in this dicitionary: `n`, `metadata`, `value`. I understand the `n` refers to the number of subjects chosen, `metadata` is the name of the column in the `participants.tsv` file. How do we interpret the `value` which is defined as "List of metadata values of the subject to be selected". In my `participants.tsv` file, there are only 3 columns - `participant_id`, `sex`, `age`. I set the `metadata` as `participant_id` but am unsure how to define the `value` key. It appears that the example use-case given in the documentation has a more detailed `participants.tsv` file. Is there any other way to use the `subject_selection` key? I tried using the same `value` as in `metadata` but ran into an error (trace shown below), and removing the `value` parameter does not help as well. Any suggestions are highly appreciated!

<details>
<summary> ValueError Trace </summary>

```
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/u114716/venv_ivado/bin/ivadomed", line 8, in <module>
    sys.exit(run_main())
  File "/home/GRAMES.POLYMTL.CA/u114716/venv_ivado/lib/python3.8/site-packages/ivadomed/main.py", line 592, in run_main
    run_command(context=context,
  File "/home/GRAMES.POLYMTL.CA/u114716/venv_ivado/lib/python3.8/site-packages/ivadomed/main.py", line 373, in run_command
    train_lst, valid_lst, test_lst = imed_loader_utils.get_subdatasets_subject_files_list(context[ConfigKW.SPLIT_DATASET],
  File "/home/GRAMES.POLYMTL.CA/u114716/venv_ivado/lib/python3.8/site-packages/ivadomed/loader/utils.py", line 219, in get_subdatasets_subject_files_list
    train_lst, valid_lst, test_lst = get_new_subject_file_split(df=df,
  File "/home/GRAMES.POLYMTL.CA/u114716/venv_ivado/lib/python3.8/site-packages/ivadomed/loader/utils.py", line 146, in get_new_subject_file_split
    participants = random.sample(df[df[m] == v]['participant_id'].unique().tolist(), n)
  File "/usr/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

</details>
 

Also, the key `n` is not intuitive for defining the number of subjects to be used. Can it be replaced with some other name like `sub`, `id` or `num_subs`?

**Comment by dyt811** [comment]
So the example given chosen two sets of subjects: "5 x disease == healthy" + "10 x disease == ms"

So in the case of "participant ID" since each participant can only has one ID, it is probably not useful to be used as selection here. 

As a simple example, maybe you can try "5 x sex == male" or "10 x sex == female" and see if it pulls up anything. 

I think it might be just simply pulling through the number of subjects matching a specific field filter, mainly used  to just get the right numbers of subjects from specific groups. when the data match metadata value and drawing N sample from it.
