### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by etetteh** [ivadomed/ivadomed#1082]
### Current behavior
```
2022-02-19 02:34:12.862 | WARNING  | ivadomed.loader.bids_dataframe:write_derivatives_dataset_description:304 - /localscratch/etetteh.57988438.0/spine_generic_enoch/derivatives/dataset_descri>
/home/etetteh/neuropoly/venv_ivadomed/lib/python3.7/site-packages/bids/layout/validation.py:149: UserWarning: The PipelineDescription field was superseded by GeneratedBy in BIDS 1.4.0. You ca>
  warnings.warn("The PipelineDescription field was superseded "
2022-02-19 02:34:18.628 | INFO     | ivadomed.loader.bids_dataframe:save:289 - Dataframe has been saved in baseline_subset_sg/bids_dataframe.csv.
Traceback (most recent call last):
  File "/home/etetteh/neuropoly/venv_ivadomed/bin/ivadomed", line 11, in <module>
    load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
  File "/home/etetteh/neuropoly/ivadomed/ivadomed/main.py", line 596, in run_main
    resume_training=bool(args.resume_training))
  File "/home/etetteh/neuropoly/ivadomed/ivadomed/main.py", line 381, in run_command
    imed_utils.generate_sha_256(context, bids_df.df, train_lst)
  File "/home/etetteh/neuropoly/ivadomed/ivadomed/utils.py", line 89, in generate_sha_256
    file_path = df_sub['path'].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

### Expected behavior
Run without the errors, 

### Steps to reproduce
I created a `.joblib` file that contains the subjects for training, validation, and testing. 

```
Example:
>>> train_list = ['subj_1', 'subj_2', 'subj_3']
>>> valid_list = ['subj_4', 'subj_5']
>>> test_list = ['subj_6']

>>> split_path = "./" + "ood_split_datasets.joblib"
>>> split_dct = {'train': train_list, 'valid': valid_list, 'test': test_list}
>>> joblib.dump(split_dct, split_path)
```

### System description
Graham (Compute Canada)

### Installed packages
<details open>
<summary> Output of <code>pip freeze</code> </summary>

```
absl-py==1.0.0+computecanada
argcomplete==2.0.0
astor==0.8.1+computecanada
bids-validator==1.9.2
boto==2.49.0+computecanada
cachetools==5.0.0
certifi==2021.10.8+computecanada
cffi==1.14.6+computecanada
charset-normalizer==2.0.12
click==8.0.3+computecanada
cloudpickle==1.6.0+computecanada
crcmod==1.7+computecanada
cryptography==36.0.1+computecanada
csv-diff==1.1
cycler==0.11.0+computecanada
Deprecated==1.2.13
dictdiffer==0.9.0+computecanada
docopt==0.6.2+computecanada
fasteners==0.17.3
formulaic==0.2.4
future==0.18.2+computecanada
gcs-oauth2-boto-plugin==2.7+computecanada
google-apitools==0.5.32+computecanada
google-auth==2.6.0
google-auth-oauthlib==0.4.6+computecanada
google-reauth==0.1.1+computecanada
grpcio==1.38.1+computecanada
gsutil==4.53+computecanada
gym==0.18.0+computecanada
httplib2==0.20.4
humanize==4.0.0
idna==3.3+computecanada
imageio==2.16.0
importlib-metadata==4.11.1
interface-meta==1.2.4
-e git+https://github.com/ivadomed/ivadomed.git@cc28e360ca2f09de51e2d4be165d8db20f9d79a2#egg=ivadomed
joblib==1.1.0+computecanada
kiwisolver==1.3.1+computecanada
loguru==0.6.0
markdown==3.3.6+computecanada
matplotlib==3.4.2+computecanada
mock==2.0.0+computecanada
monotonic==1.6
networkx==2.6.3+computecanada
nibabel==3.2.2
num2words==0.5.10+computecanada
numpy==1.21.4+computecanada
oauth2client==4.1.3+computecanada
oauthlib==3.2.0
packaging==21.3+computecanada
pandas==1.3.5+computecanada
pbr==5.8.1+computecanada
pillow==8.4.0+computecanada
protobuf==3.19.4
pyasn1==0.4.8+computecanada
pyasn1-modules==0.2.8+computecanada
pybids==0.14.0
pycparser==2.21+computecanada
pyglet==1.5.0
pyOpenSSL==22.0.0
pyparsing==2.4.7+computecanada
python-dateutil==2.8.2+computecanada
pytz==2021.3+computecanada
pyu2f==0.1.4+computecanada
pywavelets==1.1.1+computecanada
requests==2.27.1+computecanada
requests-oauthlib==1.3.1
retry-decorator==1.1.1+computecanada
rsa==4.8+computecanada
scikit-image==0.18.2+computecanada
scikit-learn==1.0.1+computecanada
scipy==1.7.3+computecanada
seaborn==0.11.2+computecanada
SimpleITK==1.2.4+computecanada
six==1.16.0+computecanada
SQLAlchemy==1.3.20+computecanada
tensorboard==2.8.0
tensorboard-data-server==0.6.1+computecanada
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
tifffile==2021.11.2+computecanada
torch==1.8.1+cu111
torchio==0.18.73
torchvision==0.9.1+cu111
tqdm==4.62.3+computecanada
typing-extensions==4.1.1
urllib3==1.26.8+computecanada
werkzeug==2.0.3+computecanada
wrapt==1.12.1+computecanada
zipp==3.7.0+computecanada
```

</details>

**Comment by uzaymacar** [comment]
Hey @etetteh, can you also add where and how to access the **data** to the **Steps to reproduce** section? My first guess is that the `subj_XXX` format doesn't load any data as the BIDS convention uses `sub-XXX`.

**Comment by etetteh** [comment]
I am using the spine-generic-processed dataset with the attached `.joblib` file that contains the subject names. I tried using the `subject directories` as in `sub-XYZ`, and also exact `subject images` as in `sub-XYZ.nii.gz`, but they all gave the same error.
Furthermore, I am attaching the  `.joblib`, since it's a public dataset.
[ood_split_datasets.joblib.zip](https://github.com/ivadomed/ivadomed/files/8102362/ood_split_datasets.joblib.zip)
et.

**Comment by etetteh** [comment]
I resolved the issue.  I recreated the `.joblib` file again, and everything works one.
However, I suspect the issue was due to 
1. the subsetting of the full dataset. 
2. potential error in creating the `.joblib` file
