### ISSUE TITLE
ValueError: Shape mismatch: im1 and im2 must have the same shape.

### ISSUE THREAD

**Issue by etetteh** [ivadomed/ivadomed#1083]
### Current behavior
I am trying to use a pre-trained model to perform inference on a different test set rather than the test subset of the "original", in order to analyze the model performance on out-of-distribution data.
I created a '.joblib' file to pass only my test data, but it resulted in the error shown below. I also added some training and valid data (although they won't be used) just for the benefit of the doubt, but I got the same error. 

Furthermore, I excluded the `.joblib` file and just passed the test data to the `config.json` file, but increased the test data percentage, but nothing changed.

### Expected behavior
Expected a successful run of the inference. 

### Steps to reproduce
`ivadomed -c test_config.json --test  --path-data <test_data_dir> --path-output <output_dir>`

<details>
<summary> An example summary message </summary>

```
Traceback (most recent call last):
  File "/Users/en_tetteh/miniforge3/envs/venv_ivadomed/bin/ivadomed", line 33, in <module>
    sys.exit(load_entry_point('ivadomed', 'console_scripts', 'ivadomed')())
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/main.py", line 593, in run_main
    run_command(context=context,
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/main.py", line 497, in run_command
    pred_metrics = imed_testing.test(model_params=model_params,
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/testing.py", line 79, in test
    metric_mgr(preds_npy, gt_npy)
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/metrics.py", line 44, in __call__
    res = metric_fn(p, gt)
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/metrics.py", line 110, in dice_score
    raise ValueError("Shape mismatch: im1 and im2 must have the same shape.")
ValueError: Shape mismatch: im1 and im2 must have the same shape.
```
</details>

### System description
Compute Canada, and also my local machine (macOS). 

### Installed packages
<details open>
<summary> Output of <code>pip freeze</code> </summary>

```
absl_py==1.0.0+computecanada
astor==0.8.1+computecanada
attrs==21.4.0+computecanada
bids-neuropoly==0.2
bids-validator==1.9.2
cachetools==5.0.0
certifi==2021.10.8+computecanada
charset-normalizer==2.0.12
click==8.0.4
csv-diff==1.1
cycler==0.11.0+computecanada
Deprecated==1.2.13
dictdiffer==0.9.0+computecanada
docopt==0.6.2+computecanada
flatbuffers==20190709135844+computecanada
fonttools==4.29.1+computecanada
formulaic==0.2.4
google-auth==2.6.0
google_auth_oauthlib==0.4.6+computecanada
grpcio==1.41.1+computecanada
h5py==3.6.0+computecanada
humanize==4.0.0
idna==3.3+computecanada
imageio==2.16.0
importlib-metadata==4.11.1
iniconfig==1.1.1+computecanada
interface-meta==1.2.4
-e git+https://github.com/etetteh/ivadomed.git@cc28e360ca2f09de51e2d4be165d8db20f9d79a2#egg=ivadomed
joblib==1.1.0+computecanada
kiwisolver==1.3.2+computecanada
loguru==0.6.0
Markdown==3.3.6+computecanada
matplotlib==3.5.1+computecanada
networkx==2.6.3+computecanada
nibabel==3.2.2
num2words==0.5.10+computecanada
numpy==1.22.2+computecanada
oauthlib==3.2.0
onnxruntime==1.8.1+computecanada
packaging==21.3+computecanada
pandas==1.4.0+computecanada
Pillow==9.0.1+computecanada
Pillow-SIMD==7.0.0.post3+computecanada
pluggy==1.0.0+computecanada
protobuf==3.19.4
py==1.11.0+computecanada
pyasn1==0.4.8+computecanada
pyasn1-modules==0.2.8+computecanada
pybids==0.14.0
pyparsing==2.4.7+computecanada
pytest==7.0.1
python-dateutil==2.8.2+computecanada
pytz==2021.3+computecanada
PyWavelets==1.2.0+computecanada
requests==2.27.1+computecanada
requests-oauthlib==1.3.1
rsa==4.8+computecanada
scikit-image==0.18.1+computecanada
scikit_learn==1.0.1+computecanada
scipy==1.8.0+computecanada
seaborn==0.11.2+computecanada
SimpleITK==1.2.4+computecanada
six==1.16.0+computecanada
SQLAlchemy==1.3.20+computecanada
tensorboard==2.8.0
tensorboard-data-server==0.6.1+computecanada
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
tifffile==2022.2.9
tomli==2.0.1+computecanada
torch==1.8.1+cu111
torchio==0.18.73
torchvision==0.9.1+cu111
tqdm==4.62.3+computecanada
typing_extensions==4.1.1
urllib3==1.26.8+computecanada
Werkzeug==2.0.3+computecanada
wrapt==1.12.1+computecanada
zipp==3.7.0+computecanada
```

</details>

Per the error report, I suspect the test data passed is not transformed into the required form, and I doubt it is machine/system dependent. 

I think the remedy is to be able to transform/process test data, that wasn't a test subset of the original data.

**Comment by jcohenadad** [comment]
@etetteh thank you for reporting this issue. I would suggest you go through the debugger to try to understand at what point this mismatch is occurring. I think it would be a good opportunity to get more into the code and show your computer skills 😊

**Comment by Nish228** [comment]
Hi, I seem to be having the same issue during testing. It seems to be related to the function dice_score in metrics.py.
