### ISSUE TITLE
Controlling randomness for reproducibility

### ISSUE THREAD

**Issue by etetteh** [ivadomed/ivadomed#1092]
The current implementation of ivadomed only sets the random number generator seed for splitting a dataset into train, validation and test sets. However, there are other sources of randomness that we need to take into consideration, such as 1) the Numpy library 2) Pytorch library 3) Python itself 4) CUDA etc. 
We may use this [reference](https://pytorch.org/docs/stable/notes/randomness.html)

The main reason is seeding the dataset splitting alone, still leaves some sources of randomness unchecked. Also, if a user decides to use a `.joblib` file to split the data as documented [here ](https://ivadomed.org/configuration_file.html#fname-split), the `random_state` won't be used, but we still need to control other sources of randomness.

**Comment by etetteh** [comment]
There are cases where the above libraries are used without instantiating a seed. Random from the python standard library for instance uses [self.seed](https://github.com/python/cpython/blob/5fd33b5926eb8c9352bf5718369b4a8d72c4bb44/Lib/random.py#L87-L94) , which when not passed will use for example the user's system time, some torch's methods/or functions has some level of randomness (data loader for instance, and also some of the seed are hard coded. I was itemizing the where these are happening, but I think we can instantiate these at the beginning of scripts where these libraries are imported.

Something like:

def set_seed(seed):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

**Comment by jcohenadad** [comment]
> Something like:

thank you @etetteh, could you please cross-reference directly to the code that defines this function? it will be easier to debug/refactor, many thanks

**Comment by etetteh** [comment]
This is my own function suggestion to be used.

**Comment by etetteh** [comment]
I will add it to the branch I am working on, and push it ASAP.

**Comment by jcohenadad** [comment]
> I will add it to the branch I am working on, and push it ASAP.

this is great! thank you Enoch. In general we prefer atomic PRs, so if it is fairly isolated could you pls do it in another PR. thx

**Comment by etetteh** [comment]
I have made the necessary changes in the respective files. I added a key in the config file under the ConfigKW, instead of having it under the SplitDatasetKW, but I am having an error. I noticed the keys under ConfigKW are wrapped in a `context`, so I have to fix that.

**Comment by jcohenadad** [comment]
> I have made the necessary changes in the respective files. I added a key in the config file under the ConfigKW, instead of having it under the SplitDatasetKW, but I am having an error. I noticed the keys under ConfigKW are wrapped in a context, so I have to fix that.

@etetteh can you please reference where you made the changes, what error you obtain, etc. as you can see from other issues/PRs we make efforts to thoroughly cross-reference, add hyperlinks to code, etc. thank you for your understanding

**Comment by etetteh** [comment]
Okay. I understand. There were a number of changes, and I have pushed them to this [branch](https://github.com/etetteh/ivadomed/tree/et/control_randomness).

This is the error I am getting. 
```
Traceback (most recent call last):
  File "_mt19937.pyx", line 178, in numpy.random._mt19937.MT19937._legacy_seeding
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/en_tetteh/miniforge3/envs/venv_ivadomed/bin/ivadomed", line 33, in <module>
    sys.exit(load_entry_point('ivadomed', 'console_scripts', 'ivadomed')())
  File "/Users/en_tetteh/miniforge3/envs/venv_ivadomed/bin/ivadomed", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/en_tetteh/miniforge3/envs/venv_ivadomed/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/en_tetteh/miniforge3/envs/venv_ivadomed/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/main.py", line 13, in <module>
    from ivadomed import evaluation as imed_evaluation
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/evaluation.py", line 9, in <module>
    from ivadomed import inference as imed_inference
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/inference.py", line 15, in <module>
    from ivadomed.loader.mri3d_subvolume_segmentation_dataset import MRI3DSubVolumeSegmentationDataset
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/loader/mri3d_subvolume_segmentation_dataset.py", line 8, in <module>
    from ivadomed import transforms as imed_transforms, postprocessing as imed_postpro
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/transforms.py", line 19, in <module>
    from ivadomed.loader import utils as imed_loader_utils
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/loader/utils.py", line 22, in <module>
    set_seed(ConfigKW.RANDOM_SEED)
  File "/Users/en_tetteh/NEUROPOLY/ivadomed/ivadomed/loader/utils.py", line 19, in set_seed
    np.random.seed(seed)
  File "mtrand.pyx", line 246, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 186, in numpy.random._mt19937.MT19937._legacy_seeding
TypeError: Cannot cast scalar from dtype('<U11') to dtype('int64') according to the rule 'safe'
```

I understand why I am getting that error, but my issue is how to make the necessary change in the [main.py](https://github.com/ivadomed/ivadomed/blob/8d42d27298d4ffc284f3da2e24d03f9e967d7c84/ivadomed/main.py) file  to access the key in the config file. I don't think we need to define a `context` (based on the config_manager.py file) in every single file. I need some help.

**Comment by uzaymacar** [comment]
Hey @etetteh I have a couple thoughts / suggestions but let me know if I'm missing something:
* You want to do `context[ConfigKW.RANDOM_SEED]` but `context` is not defined in `ivadomed/loader/utils` which is the current call place for `set_seed`
* Instead of calling `set_seed` [here](https://github.com/etetteh/ivadomed/blob/aca753bd359e7fbf50a75fe4307f7eae90a66587/ivadomed/loader/utils.py#L22) we probably want to call inside `main.py`
* `run_command` includes `context` as an input parameter so that might be one place to call `set_seed`. This is also good for the visibility and logical ordering of the function and as we usually want to set seeds the first thing in the script.

**Comment by etetteh** [comment]
Thank you @uzaymacar, and yes I wanted to call context inside the respective.
It turns out, I don't necessarily have to seed everything, specifically the randomness in the `transforms.py` file and others. Anyways, I have resolved the error, and added the `set_seed` to the `main.py` file, which then goes to the `loader/utils.py` and `training.py`. 

If we have to set the `set_seed` at the top of other/all scripts, one way would be to put the `args` and `context` and separate script, and import the `context`.

**Comment by jcohenadad** [comment]
@etetteh can you please open a PR so we can follow your development

**Comment by dyt811** [comment]
Linked PR here: https://github.com/ivadomed/ivadomed/pull/1093 

I recommend all who read this to move subsequent discussions to there for future references.
