### ISSUE TITLE
`whl` missing a dependency: `torchvision`

### ISSUE THREAD

**Issue by kousu** [ivadomed/ivadomed#1130]
### Current behavior

If you install ivadomed from what we have published on [pypi](https://pypi.org/project/ivadomed) all by itself, `ivadomed.transforms` (and probably other parts) are broken because

> ModuleNotFoundError: No module named 'torchvision' 

(Originally found in https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/6359735921?check_suite_focus=true (part of https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3790))

### Expected behavior

`torchvision`, being a direct dependency of ivadomed, should be installed when ivadomed is.

### Steps to reproduce

1. Install `ivadomed` with `pip` in a fresh environment
2. Try to `import ivadomed.transforms`

<details>

```
p115628@joplin:~$ python3 -m venv ivadomed_env
p115628@joplin:~$ source ivadomed_env/bin/activate
(ivadomed_env) p115628@joplin:~$ pip install --upgrade pip
Collecting pip
  Downloading pip-22.1-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 32.7 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-22.1
(ivadomed_env) p115628@joplin:~$ pip install ivadomed
Collecting ivadomed
  Using cached ivadomed-2.9.5-py3-none-any.whl (223 kB)
Collecting loguru~=0.5
  Using cached loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting pillow>=7.0.0
  Downloading Pillow-9.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 63.6 MB/s eta 0:00:00
Collecting pandas~=1.1
  Downloading pandas-1.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 65.5 MB/s eta 0:00:00
Collecting torchio>=0.18.68
  Downloading torchio-0.18.77-py2.py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.5/167.5 kB 52.7 MB/s eta 0:00:00
Collecting scikit-image~=0.17
  Downloading scikit_image-0.19.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 61.6 MB/s eta 0:00:00
Collecting nibabel~=3.2
  Using cached nibabel-3.2.2-py3-none-any.whl (3.3 MB)
Collecting scikit-learn>=0.20.3
  Downloading scikit_learn-1.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.0/31.0 MB 39.4 MB/s eta 0:00:00
Collecting pyparsing<3,>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting onnxruntime==1.7.0
  Downloading onnxruntime-1.7.0-cp38-cp38-manylinux2014_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 77.8 MB/s eta 0:00:00
Collecting seaborn~=0.11
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting tqdm>=4.30
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting pybids>=0.14.0
  Using cached pybids-0.15.1-py3-none-any.whl (3.2 MB)
Collecting scipy
  Downloading scipy-1.8.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.6/41.6 MB 32.7 MB/s eta 0:00:00
Collecting csv-diff>=1.0
  Using cached csv_diff-1.1-py3-none-any.whl (12 kB)
Collecting matplotlib>=3.3.0
  Downloading matplotlib-3.5.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 75.1 MB/s eta 0:00:00
Collecting tensorboard>=1.15.0
  Using cached tensorboard-2.9.0-py3-none-any.whl (5.8 MB)
Collecting joblib~=1.0
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting protobuf
  Downloading protobuf-3.20.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 72.0 MB/s eta 0:00:00
Collecting numpy>=1.16.6
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting dictdiffer
  Using cached dictdiffer-0.9.0-py2.py3-none-any.whl (16 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 89.3 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./ivadomed_env/lib/python3.8/site-packages (from nibabel~=3.2->ivadomed) (44.0.0)
Collecting pytz>=2020.1
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting sqlalchemy<1.4.0.dev0
  Downloading SQLAlchemy-1.3.24-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 85.3 MB/s eta 0:00:00
Collecting bids-validator
  Using cached bids_validator-1.9.3-py2.py3-none-any.whl (21 kB)
Collecting formulaic<0.4,>=0.2.4
  Using cached formulaic-0.3.4-py3-none-any.whl (68 kB)
Collecting num2words
  Using cached num2words-0.5.10-py3-none-any.whl (101 kB)
Collecting imageio>=2.4.1
  Downloading imageio-2.19.2-py3-none-any.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 82.5 MB/s eta 0:00:00
Collecting networkx>=2.2
  Downloading networkx-2.8-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 85.5 MB/s eta 0:00:00
Collecting tifffile>=2019.7.26
  Downloading tifffile-2022.5.4-py3-none-any.whl (195 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.6/195.6 kB 62.8 MB/s eta 0:00:00
Collecting PyWavelets>=1.1.1
  Downloading PyWavelets-1.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 77.2 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting absl-py>=0.4
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting grpcio>=1.24.3
  Downloading grpcio-1.46.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 77.2 MB/s eta 0:00:00
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting wheel>=0.26
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 79.9 MB/s eta 0:00:00
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.6.6-py2.py3-none-any.whl (156 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.7/156.7 kB 57.4 MB/s eta 0:00:00
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 93.6 MB/s eta 0:00:00
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.7-py3-none-any.whl (97 kB)
Collecting werkzeug>=1.0.1
  Using cached Werkzeug-2.1.2-py3-none-any.whl (224 kB)
Collecting humanize
  Using cached humanize-4.1.0-py3-none-any.whl (101 kB)
Collecting torch>=1.1
  Downloading torch-1.11.0-cp38-cp38-manylinux1_x86_64.whl (750.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.6/750.6 MB 2.5 MB/s eta 0:00:00
Collecting Deprecated
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting SimpleITK!=2.0.*,!=2.1.1.1
  Downloading SimpleITK-2.1.1.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (48.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 MB 27.7 MB/s eta 0:00:00
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting interface-meta<2.0.0,>=1.2.0
  Using cached interface_meta-1.3.0-py3-none-any.whl (14 kB)
Collecting astor>=0.8
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting wrapt>=1.0
  Downloading wrapt-1.14.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.0/81.0 kB 31.7 MB/s eta 0:00:00
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.1.0-py3-none-any.whl (9.2 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 55.8 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.8-py3-none-any.whl (39 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata>=4.4
  Using cached importlib_metadata-4.11.3-py3-none-any.whl (18 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting docopt>=0.6.2
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting zipp>=0.5
  Using cached zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 35.7 MB/s eta 0:00:00
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.0-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.5/151.5 kB 53.5 MB/s eta 0:00:00
Using legacy 'setup.py install' for docopt, since package 'wheel' is not installed.
Installing collected packages: tensorboard-plugin-wit, SimpleITK, pytz, pyasn1, docopt, dictdiffer, certifi, bids-validator, zipp, wrapt, wheel, werkzeug, urllib3, typing-extensions, tqdm, threadpoolctl, tensorboard-data-server, sqlalchemy, six, rsa, pyparsing, pyasn1-modules, protobuf, pillow, oauthlib, numpy, num2words, networkx, loguru, kiwisolver, joblib, interface-meta, idna, humanize, fonttools, cycler, click, charset-normalizer, cachetools, astor, torch, tifffile, scipy, requests, PyWavelets, python-dateutil, packaging, onnxruntime, importlib-metadata, imageio, grpcio, google-auth, Deprecated, csv-diff, absl-py, scikit-learn, scikit-image, requests-oauthlib, pandas, nibabel, matplotlib, markdown, torchio, seaborn, google-auth-oauthlib, formulaic, tensorboard, pybids, ivadomed
  Running setup.py install for docopt ... done
Successfully installed Deprecated-1.2.13 PyWavelets-1.3.0 SimpleITK-2.1.1.2 absl-py-1.0.0 astor-0.8.1 bids-validator-1.9.3 cachetools-5.1.0 certifi-2021.10.8 charset-normalizer-2.0.12 click-8.1.3 csv-diff-1.1 cycler-0.11.0 dictdiffer-0.9.0 docopt-0.6.2 fonttools-4.33.3 formulaic-0.3.4 google-auth-2.6.6 google-auth-oauthlib-0.4.6 grpcio-1.46.1 humanize-4.1.0 idna-3.3 imageio-2.19.2 importlib-metadata-4.11.3 interface-meta-1.3.0 ivadomed-2.9.5 joblib-1.1.0 kiwisolver-1.4.2 loguru-0.6.0 markdown-3.3.7 matplotlib-3.5.2 networkx-2.8 nibabel-3.2.2 num2words-0.5.10 numpy-1.22.3 oauthlib-3.2.0 onnxruntime-1.7.0 packaging-21.3 pandas-1.4.2 pillow-9.1.1 protobuf-3.20.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pybids-0.15.1 pyparsing-2.4.7 python-dateutil-2.8.2 pytz-2022.1 requests-2.27.1 requests-oauthlib-1.3.1 rsa-4.8 scikit-image-0.19.2 scikit-learn-1.1.0 scipy-1.8.0 seaborn-0.11.2 six-1.16.0 sqlalchemy-1.3.24 tensorboard-2.9.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 threadpoolctl-3.1.0 tifffile-2022.5.4 torch-1.11.0 torchio-0.18.77 tqdm-4.64.0 typing-extensions-4.2.0 urllib3-1.26.9 werkzeug-2.1.2 wheel-0.37.1 wrapt-1.14.1 zipp-3.8.0
(ivadomed_env) p115628@joplin:~$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ivadomed.transforms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/GRAMES.POLYMTL.CA/p115628/ivadomed_env/lib/python3.8/site-packages/ivadomed/transforms.py", line 16, in <module>
    from torchvision import transforms as torchvision_transforms
ModuleNotFoundError: No module named 'torchvision' 
```

</details>

### System description

Found on Ubuntu, but I'm pretty sure this is OS-agnostic:

```
p115628@joplin:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by dyt811** [comment]
Odd. Not sure how come torchvision is missing. What happened before I wonder. Eitherway, we should get a hotpatch release out to remedy this ASAP.

**Comment by kousu** [comment]
Thanks Yang.

The problem is that the pip version pulls its dependencies here:

https://github.com/ivadomed/ivadomed/blob/bd904e5e139fa6a437abfc225216f6057824f1e3/setup.py#L38

from

https://github.com/ivadomed/ivadomed/blob/bd904e5e139fa6a437abfc225216f6057824f1e3/setup.py#L7-L8

from

https://github.com/ivadomed/ivadomed/blob/bd904e5e139fa6a437abfc225216f6057824f1e3/requirements_common.txt#L1-L24

which doesn't include `torchvision`.

`torchvision` is listed as a dependency in 

https://github.com/ivadomed/ivadomed/blob/bd904e5e139fa6a437abfc225216f6057824f1e3/requirements.txt#L4-L13

and

https://github.com/ivadomed/ivadomed/blob/bd904e5e139fa6a437abfc225216f6057824f1e3/requirements_gpu.txt#L4-L7

but notice neither of those get pulled in by setup.py.

So this works when tested on our internal infra, where you follow [GPU installation](https://ivadomed.org/installation.html#step-3-install-torch-and-torchvision-with-cpu-or-gpu-support), and probably in your dev environments where you just have torchvision installed ambiently.

**Comment by kousu** [comment]
:smile: thanks for owning it. Maybe the reason things ended up like this is related to the CPU/GPU installation problem (https://github.com/pytorch/pytorch/issues/26340) you've been trying to address in #1000, and I'm trying to improve in a smaller way in https://github.com/ivadomed/ivadomed/pull/1129.

I think if you integrate https://github.com/ivadomed/ivadomed/pull/1129 first then it will be easier to fix this.

**Comment by kousu** [comment]
Actually I've included a fix for this in #1129, since they're so tightly intertwined anyway.

**Comment by kanishk16** [comment]
IIUC, CI is designed similar to how we would expect users to install ivadomed. Moreover, I guess we might even miss out torch if  `torchio` isn't listed as a dependency https://github.com/ivadomed/ivadomed/blob/bd904e5e139fa6a437abfc225216f6057824f1e3/.github/workflows/run_tests.yml#L58-L67

**Comment by kousu** [comment]
Maybe worth getting everyone on the team to read https://blog.ionelmc.ro/2014/05/25/python-packaging/. Particularly to emphasize that, in python, due to the fact that `.` is on PYTHONPATH by default, and the way `pkg_resources` works, a built library is subtly different from one `pip install -e .` which is subtly dw ifferent from just `import ivadomed` run from from the ivadomed folder.

The only really safe thing to do AFAIK is to first build the complete wheel, install it, then run the rests. And that why https://blog.ionelmc.ro/2014/05/25/python-packaging/ emphasizes the 'src/' layout: it makes it unlikely you'll accidentally run code from your source code -- it forces you to build and install the package before your tests can run:

> This constraint has beneficial implications in both testing and packaging:
>
> *    You will be forced to test the installed code (e.g.: by installing in a virtualenv). This will ensure that the deployed code works (it's packaged correctly) - otherwise your tests will fail. Early. Before you can publish a broken distribution.
> *    You will be forced to install the distribution. If you ever uploaded a distribution on [PyPI](https://pypi.python.org/pypi) with missing modules or broken dependencies it's because you didn't test the installation. Just beeing able to successfuly build the sdist doesn't guarantee it will actually install!

**Comment by dyt811** [comment]
So this is partially the problem PR#1000 has been trying to address and highly related to Torch installation. 

The current installation instruction never stopped at `pip install` stage either and any PyPI installation (Step 2) is never complete per latest installation instructions and Step 3 is mandatory for CPU or GPU installation as the version of Torchvision (along with Torch) are hardware specific and needs to be pulled from the extra-index-URL link (and apparently their versions need to be aligned). 

i.e. default ivadomed pypi install is incomplete until Step 3 is completed. 

What would be interesting is to test perhaps if the latest torchvision is backward compatible with earlier torch version.  But eitherway, we will most likely resolve this issue along with PR1000 by defaulting to CPU and only extend to GPU.

**Comment by kousu** [comment]
For the record: this is basically a duplicate of https://github.com/ivadomed/ivadomed/issues/861. @joshuacwnewton called this bug months ago, though IMO the impact is broader than just downstream: people should be able to `pip install` stuff without having to go learn too much niche stuff.
