### ISSUE TITLE
IndexError: list index out of range when testing model

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1256]
Upton model testing, I am getting this:

Input: 
~~~
ivadomed --test -c ~/code/model_seg_ms_mp2rage/config/config_seg_lesion.json --path-output model_seg_lesion_mp2rage_20230102_172530
~~~

<details><summary>Terminal output</summary>

```console
2023-01-03 14:51:47.672 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   is_2d: False
2023-01-03 14:51:47.672 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   final_activation: sigmoid
2023-01-03 14:51:47.672 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   folder_name: model_seg_lesion_mp2rage
2023-01-03 14:51:47.672 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   applied: True
2023-01-03 14:51:47.672 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   length_3D: [32, 32, 16]
2023-01-03 14:51:47.672 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   stride_3D: [1, 1, 1]
2023-01-03 14:51:47.672 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   attention: True
2023-01-03 14:51:47.673 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   n_filters: 8
2023-01-03 14:51:47.673 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   in_channel: 1
2023-01-03 14:51:47.673 | INFO     | ivadomed.utils:display_selected_model_spec:185 -   out_channel: 1
2023-01-03 14:51:51.655 | INFO     | ivadomed.loader.bids_dataframe:save:319 - Dataframe has been saved in model_seg_lesion_mp2rage_20230102_172530/bids_dataframe.csv.
2023-01-03 14:51:51.659 | WARNING  | ivadomed.loader.utils:split_dataset:110 - After splitting: train, validation and test fractions are respectively 0.596, 0.309 and 0.096 of participant_id.
2023-01-03 14:51:52.062 | INFO     | ivadomed.utils:display_selected_transfoms:195 - Selected transformations for the ['testing'] dataset:
2023-01-03 14:51:52.063 | INFO     | ivadomed.utils:display_selected_transfoms:197 -    Resample: {'hspace': 1, 'wspace': 1, 'dspace': 1}
2023-01-03 14:51:52.063 | INFO     | ivadomed.utils:display_selected_transfoms:197 -    CenterCrop: {'size': [32, 32, 64]}
2023-01-03 14:51:52.063 | INFO     | ivadomed.utils:display_selected_transfoms:197 -    NormalizeInstance: {'applied_to': ['im']}
Loading dataset: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 767.31it/s]
2023-01-03 14:51:55.338 | INFO     | ivadomed.loader.loader:load_dataset:118 - Loaded 833 volumes of shape [32, 32, 16] for the testing set.
2023-01-03 14:51:55.339 | INFO     | ivadomed.testing:test:52 - Loading model: model_seg_lesion_mp2rage_20230102_172530/best_model.pt
Inference - Iteration 0:   0%|                                                                                                                                          | 0/53 [00:00<?, ?it/s]2023-01-03 14:51:57.945 | INFO     | ivadomed.visualize:get_input_array:288 - Input Array Size: 
2023-01-03 14:51:57.945 | INFO     | ivadomed.visualize:get_output_array:294 - Output Array Size: 
2023-01-03 14:51:58.053 | INFO     | ivadomed.visualize:get_input_array:288 - Input Array Size: 
2023-01-03 14:51:58.053 | INFO     | ivadomed.visualize:get_output_array:294 - Output Array Size: 
Inference - Iteration 0:   0%|                                                                                                                                          | 0/53 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/.conda/envs/ivadomed/bin/ivadomed", line 33, in <module>
    sys.exit(load_entry_point('ivadomed', 'console_scripts', 'ivadomed')())
  File "/home/GRAMES.POLYMTL.CA/p101317/code/ivadomed/ivadomed/main.py", line 623, in run_main
    run_command(context=context,
  File "/home/GRAMES.POLYMTL.CA/p101317/code/ivadomed/ivadomed/main.py", line 527, in run_command
    pred_metrics = imed_testing.test(model_params=model_params,
  File "/home/GRAMES.POLYMTL.CA/p101317/code/ivadomed/ivadomed/testing.py", line 77, in test
    preds_npy, gt_npy = run_inference(test_loader, model, model_params, testing_params, str(path_3Dpred),
  File "/home/GRAMES.POLYMTL.CA/p101317/code/ivadomed/ivadomed/testing.py", line 154, in run_inference
    imed_visualize.save_feature_map(batch, "attentionblock2", str(Path(ofolder).parent), model, input_samples,
  File "/home/GRAMES.POLYMTL.CA/p101317/code/ivadomed/ivadomed/visualize.py", line 222, in save_feature_map
    path = batch["input_metadata"][0][i]["input_filenames"]
IndexError: list index out of range
```

</details>

<details><summary>JSON config file</summary>

```JSON
{
    "command": "train",
    "gpu_ids": [5],
    "path_output": "/home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/model_seg_lesion_mp2rage_20230102_144854",
    "model_name": "model_seg_lesion_mp2rage",
    "debugging": false,
    "object_detection_params": {
        "object_detection_path": null,
        "safety_factor": [1.0, 1.0, 1.0]
    },
    "wandb": {
        "wandb_api_key": "9095e2bc9e4ab445d478c9c8a81759ae908be8c6",
        "project_name": "basel-mp2rage-lesion",
        "group_name": "3D-noAttn-test",
        "run_name": "run-01",
        "log_grads_every": 100
    },
    "loader_parameters": {
        "path_data": ["/home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/data_seg_mp2rage_20221220_124553/data_processed_lesionseg"],
        "subject_selection": {"n": [], "metadata": [], "value": []},
        "target_suffix": ["_lesion-manualHaris"],
        "extensions": [".nii.gz"],
        "roi_params": {
            "suffix": null,
            "slice_filter_roi": null
        },
        "contrast_params": {
            "training_validation": ["UNIT1"],
            "testing": ["UNIT1"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": true
        },
        "slice_axis": "axial",
        "multichannel": false,
        "soft_gt": false,
        "bids_validate": true
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 42,
        "split_method" : "participant_id",
        "data_testing": {"data_type": null, "data_value":[]},
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.1
    },
    "training_parameters": {
        "batch_size": 16,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 50,
            "early_stopping_patience": 50,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 0.001,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-3
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.1,
        "final_activation": "sigmoid",
        "depth": 3
    },
    "FiLMedUnet": {
        "applied": false,
        "metadata": "contrasts",
        "film_layers": [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    },
    "Modified3DUNet": {
        "applied": true,
        "length_3D": [32, 32, 16],
        "stride_3D": [1, 1, 1],
        "attention": true,
        "n_filters": 8
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {
        "remove_noise": {"thr": -1},
        "keep_largest": {},
        "binarize_prediction": {"thr": 0.5},
        "uncertainty": {"thr": -1, "suffix": "_unc-vox.nii.gz"},
        "fill_holes": {},
        "remove_small": {"unit": "vox", "thr": 3}
    },
    "evaluation_parameters": {
        "target_size": {"unit": "vox", "thr": [20, 100]},
        "overlap": {"unit": "vox", "thr": 3}
    },
    "transformation": {
        "Resample": {"hspace": 1, "wspace": 1, "dspace": 1},
        "CenterCrop": {"size": [32, 32, 64]},
	"NormalizeInstance": {"applied_to": ["im"]}
    }
}

```

</details>

**Comment by jcohenadad** [comment]
Hum, I tried with another model, without the attention module, and it works as expected. 

<details><summary>Terminal output</summary>

```console
Evaluation: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  5.19it/s]
2023-01-03 16:28:30.064 | INFO     | ivadomed.evaluation:evaluate:117 -                 vol_pred_class0  vol_gt_class0  rvd_class0  avd_class0  dice_class0  ...  lfdr_21-100vox_class0  lfdr_101-INFvox_class0  ltpr_0-20vox_class0  n_0-20vox  lfdr_0-20vox_class0
image_id                                                                             ...                                                                                                    
sub-P025_UNIT1             61.0          176.0    0.653409    0.653409     0.497890  ...                    NaN                     NaN                  NaN        NaN                  NaN
sub-P098_UNIT1            131.0          275.0    0.523636    0.523636     0.502463  ...                    NaN                     0.0                  0.0        1.0                  NaN
sub-P017_UNIT1              0.0            0.0         NaN         NaN          NaN  ...                    NaN                     NaN                  NaN        NaN                  NaN
sub-P146_UNIT1            460.0         1035.0    0.555556    0.555556     0.602007  ...                    NaN                     0.0                  NaN        NaN                  NaN
sub-P175_UNIT1             49.0           81.0    0.395062    0.395062     0.692308  ...                    0.0                     NaN                  NaN        NaN                  NaN

[5 rows x 22 columns]

```

</details>

<details><summary>JSON config file</summary>


```JSON
{
    "command": "train",
    "gpu_ids": [5],
    "path_output": "/home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/model_seg_lesion_mp2rage_20230102_144854",
    "model_name": "model_seg_lesion_mp2rage",
    "debugging": true,
    "object_detection_params": {
        "object_detection_path": null,
        "safety_factor": [1.0, 1.0, 1.0]
    },
    "wandb": {
        "wandb_api_key": "9095e2bc9e4ab445d478c9c8a81759ae908be8c6",
        "project_name": "basel-mp2rage-lesion",
        "group_name": "3D-noAttn-Crop32x32x96",
        "run_name": "run-01",
        "log_grads_every": 100
    },
    "loader_parameters": {
        "path_data": ["/home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/data_seg_mp2rage_20221220_124553/data_processed_lesionseg"],
        "subject_selection": {"n": [], "metadata": [], "value": []},
        "target_suffix": ["_lesion-manualHaris"],
        "extensions": [".nii.gz"],
        "roi_params": {
            "suffix": null,
            "slice_filter_roi": null
        },
        "contrast_params": {
            "training_validation": ["UNIT1"],
            "testing": ["UNIT1"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": true
        },
        "slice_axis": "axial",
        "multichannel": false,
        "soft_gt": false,
        "bids_validate": true
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 42,
        "split_method" : "participant_id",
        "data_testing": {"data_type": null, "data_value":[]},
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.1
    },
    "training_parameters": {
        "batch_size": 16,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 50,
            "early_stopping_patience": 50,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 0.001,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-3
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.1,
        "final_activation": "sigmoid",
        "depth": 3
    },
    "FiLMedUnet": {
        "applied": false,
        "metadata": "contrasts",
        "film_layers": [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    },
    "Modified3DUNet": {
        "applied": true,
        "length_3D": [32, 32, 16],
        "stride_3D": [1, 1, 1],
        "attention": false,
        "n_filters": 8
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {
        "remove_noise": {"thr": -1},
        "keep_largest": {},
        "binarize_prediction": {"thr": 0.5},
        "uncertainty": {"thr": -1, "suffix": "_unc-vox.nii.gz"},
        "fill_holes": {},
        "remove_small": {"unit": "vox", "thr": 3}
    },
    "evaluation_parameters": {
        "target_size": {"unit": "vox", "thr": [20, 100]},
        "overlap": {"unit": "vox", "thr": 3}
    },
    "transformation": {
        "Resample": {"hspace": 1, "wspace": 1, "dspace": 1},
        "CenterCrop": {"size": [32, 32, 80]},
	"NormalizeInstance": {"applied_to": ["im"]}
    }
}
```

</details>
