### ISSUE TITLE
Issue training models ( raise source.error("bad escape %s" % escape, len(escape)) re.error: bad escape \m at position 10)

### ISSUE THREAD

**Issue by GrimmSnark** [ivadomed/ivadomed#1294]
## Issue description
Hello,

So I am trying to train some microscopy segmentation models. I have run into a number of issues getting my data to load into the BIDS format. It passes the BIDS validator web app with no errors and will at least run up until the BIDS validator step. I think it is to do with the regex and the windows 10 OS I am running on. See the below anaconda output.

At the moment I am just trynig to train the example data set from axondeepseg so that I know it will work. 

```
(axondeepsegEnv1) D:\Data\ivadomedTest\data_axondeepseg_sem>ivadomed -c config_microscopy.json
2023-06-02 11:54:32.318 | INFO     | ivadomed.utils:init_ivadomed:454 -
ivadomed (2.9.7)

2023-06-02 11:54:32.321 | INFO     | ivadomed.config_manager:_display_differing_keys:153 - Adding the following keys to the configuration file
2023-06-02 11:54:32.322 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     log_file: log
2023-06-02 11:54:32.322 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     loader_parameters: is_input_dropout: False
2023-06-02 11:54:32.323 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     lr_scheduler: base_lr: 1e-05
2023-06-02 11:54:32.323 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     lr_scheduler: max_lr: 0.01
2023-06-02 11:54:32.323 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     uncertainty: {'epistemic': False, 'aleatoric': False, 'n_it': 0}
2023-06-02 11:54:32.324 | INFO     | ivadomed.config_manager:_display_differing_keys:155 -

2023-06-02 11:54:32.325 | INFO     | ivadomed.utils:get_command:387 - No CLI argument given for command: ( --train | --test | --segment ). Will check config file for command...
2023-06-02 11:54:32.325 | INFO     | ivadomed.utils:get_path_output:404 - CLI flag --path-output not used to specify output directory. Will check config file for directory...
2023-06-02 11:54:32.326 | INFO     | ivadomed.utils:get_path_data:417 - CLI flag --path-data not used to specify BIDS data directory. Will check config file for directory...
2023-06-02 11:54:32.327 | INFO     | ivadomed.main:set_output_path:215 - Output path already exists: D:/Data/ivadomedTest/data_axondeepseg_sem/output
2023-06-02 11:54:32.390 | INFO     | ivadomed.utils:define_device:160 - Cuda is not available.
2023-06-02 11:54:32.391 | INFO     | ivadomed.utils:define_device:161 - Working on cpu.
2023-06-02 11:54:32.392 | INFO     | ivadomed.utils:display_selected_model_spec:176 - Selected architecture: Unet, with the following parameters:
2023-06-02 11:54:32.394 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   dropout_rate: 0.2
2023-06-02 11:54:32.394 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   bn_momentum: 0.1
2023-06-02 11:54:32.395 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   depth: 4
2023-06-02 11:54:32.395 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   is_2d: True
2023-06-02 11:54:32.396 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   final_activation: sigmoid
2023-06-02 11:54:32.396 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   length_2D: [256, 256]
2023-06-02 11:54:32.397 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   stride_2D: [244, 244]
2023-06-02 11:54:32.397 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   folder_name: model_seg_rat_axon-myelin_sem
2023-06-02 11:54:32.398 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   in_channel: 1
2023-06-02 11:54:32.399 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   out_channel: 3
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\Scripts\ivadomed.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\ivadomed\main.py", line 623, in run_main
    run_command(context=context,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\ivadomed\main.py", line 398, in run_command
    bids_df = BidsDataframe(loader_params, path_output, derivatives=True,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\ivadomed\loader\bids_dataframe.py", line 72, in __init__
    self.create_bids_dataframe()
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\ivadomed\loader\bids_dataframe.py", line 113, in create_bids_dataframe
    layout = pybids.BIDSLayout(str(path_data), config=self.bids_config, indexer=indexer,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\bids\layout\layout.py", line 176, in __init__
    indexer(self)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\bids\layout\index.py", line 141, in __call__
    self._include_patterns = [
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\bids\layout\index.py", line 142, in <listcomp>
    _regexfy(patt, root=self._layout._root) for patt in listify(force)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\bids\layout\index.py", line 28, in _regexfy
    return re.compile(r"^/" + str(patt) + r".*")
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\re.py", line 252, in compile
    return _compile(pattern, flags)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_parse.py", line 525, in _parse
    code = _escape(source, this, state)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_parse.py", line 426, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \m at position 10

(axondeepsegEnv1) D:\Data\ivadomedTest\data_axondeepseg_sem>

```

### System description

Win 10

### Installed packages

<details open>
<summary> Output of <code>pip freeze</code> </summary>

```
(axondeepsegEnv1) D:\Data\ivadomedTest\data_axondeepseg_sem>pip freeze
absl-py==1.4.0
alabaster==0.7.13
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1666191106763/work/dist
app-model==0.1.4
appdirs==1.4.4
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///D:/bld/argon2-cffi-bindings_1666850778155/work
astor==0.8.1
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
atomicwrites==1.4.0
attrs==23.1.0
-e git+https://github.com/neuropoly/axondeepseg.git@a5482ded656d3fd9e830385c218239adef631f35#egg=AxonDeepSeg
Babel==2.12.1
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1680888073205/work
bids-validator==1.11.0
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1674535352125/work
brotlipy==0.7.0
build==0.10.0
cachetools==5.3.0
cachey==0.2.1
certifi==2023.5.7
cffi @ file:///C:/b/abs_49n3v2hyhr/croot/cffi_1670423218144/work
charset-normalizer==2.1.1
click @ file:///D:/bld/click_1666798499870/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1674202310934/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
coloredlogs==15.0.1
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1679481329611/work
contextlib2 @ file:///home/conda/feedstock_root/build_artifacts/contextlib2_1624848568296/work
contourpy @ file:///C:/b/abs_d5rpy288vc/croots/recipe/contourpy_1663827418189/work
coverage @ file:///D:/bld/coverage_1682862384253/work
cryptography @ file:///C:/b/abs_b7d7drzbky/croot/cryptography_1673298763653/work
csv-diff==1.1
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
cytoolz @ file:///D:/bld/cytoolz_1657553574946/work
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1683908660643/work
debugpy @ file:///D:/bld/debugpy_1680755540111/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
Deprecated==1.2.13
dictdiffer==0.9.0
docker-pycreds==0.4.0
docopt==0.6.2
docstring-parser==0.15
docutils==0.17.1
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
et-xmlfile @ file:///home/conda/feedstock_root/build_artifacts/et_xmlfile_1674664118162/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1678703645500/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1684761244589/work/dist
flatbuffers==23.5.9
flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1684084314667/work/source/flit_core
fonttools==4.25.0
formulaic==0.5.2
freetype-py==2.4.0
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1683494881189/work
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.18.1
google-auth-oauthlib==1.0.0
graphlib-backport==1.0.3
greenlet==2.0.2
grpcio==1.54.2
h5py @ file:///D:/bld/h5py_1617739735319/work
HeapDict==1.0.1
hsluv==5.0.3
humanfriendly==10.0
humanize==4.6.0
idna @ file:///C:/b/abs_bdhbebrioa/croot/idna_1666125572046/work
imagecodecs-lite @ file:///D:/bld/imagecodecs-lite_1649682774772/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1683031833737/work
imagesize==1.4.1
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1682176699712/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1676919000169/work
in-n-out==0.1.7
iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work
interface-meta==1.3.0
ipykernel @ file:///D:/bld/ipykernel_1684162977766/work
ipython==8.12.2
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1680023138361/work
ivadomed==2.9.7
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1663332044897/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1669810440410/work
jupyter @ file:///D:/bld/jupyter_1670249824040/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1678118109161/work
jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/jupyter_events_1673559782596/work
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1681432441054/work
jupyter_core @ file:///D:/bld/jupyter_core_1678994312980/work
jupyter_server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1679073341944/work
jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1673491454549/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649936611996/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1684239754370/work
kiwisolver @ file:///D:/bld/kiwisolver_1657953191714/work
lazy_loader==0.2
locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
loguru @ file:///D:/bld/loguru_1681126395444/work
magicgui==0.7.2
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe @ file:///D:/bld/markupsafe_1674135937271/work
matplotlib @ file:///C:/b/abs_49b2acwxd4/croot/matplotlib-suite_1679593486357/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mdurl==0.1.2
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1675771498296/work
mpmath==1.3.0
munkres==1.1.4
mypy-extensions==1.0.0
napari==0.4.17
napari-ADS @ file:///C:/ADS/axondeepseg/plugins
napari-console==0.0.8
napari-plugin-engine==0.2.0
napari-svg==0.1.6
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1683202081046/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1682452223743/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1683636231832/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1679336765223/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1680692919326/work
nibabel @ file:///home/conda/feedstock_root/build_artifacts/nibabel_1644264968592/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1680870634737/work
notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1682360583588/work
npe2==0.7.0
num2words==0.5.12
numpy==1.24.3
numpydoc==1.5.0
oauthlib==3.2.2
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
onnxruntime==1.7.0
openpyxl @ file:///D:/bld/openpyxl_1682610949304/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==1.4.4
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1681246756246/work
pathtools==0.1.2
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==9.5.0
Pint==0.21
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1683850015520/work
pluggy @ file:///C:/ci/pluggy_1648042776090/work
prettytable @ file:///home/conda/feedstock_root/build_artifacts/prettytable_1681201605171/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1674535637125/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
protobuf==4.23.1
psutil @ file:///D:/bld/psutil_1681775153467/work
psygnal==0.9.0
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
py @ file:///opt/conda/conda-bld/py_1644396412707/work
pyasn1==0.5.0
pyasn1-modules==0.3.0
pybids==0.16.1
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==1.10.7
pydicom @ file:///home/conda/feedstock_root/build_artifacts/pydicom_1668525185822/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
PyOpenGL==3.1.6
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing==2.4.7
pyproject_hooks==1.0.0
PyQt5==5.12.3
PyQt5_sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
pyreadline @ file:///D:/bld/pyreadline_1667055513906/work
pyreadline3==3.4.1
pyrsistent @ file:///D:/bld/pyrsistent_1672681635682/work
PySocks @ file:///C:/ci/pysocks_1605287845585/work
pytest==7.3.1
pytest-cov @ file:///home/conda/feedstock_root/build_artifacts/pytest-cov_1664412836798/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1677079630776/work
pytomlpp==1.0.13
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
PyWavelets @ file:///C:/b/abs_a8r4b1511a/croot/pywavelets_1670425185881/work
pywin32==306
pywinpty @ file:///D:/bld/pywinpty_1672753227989/work/target/wheels/pywinpty-2.0.10-cp38-none-win_amd64.whl
PyYAML @ file:///D:/bld/pyyaml_1648757284286/work
pyzmq @ file:///D:/bld/pyzmq_1679317113159/work
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole-base_1683329453903/work
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1680148448366/work
raven==6.10.0
requests @ file:///C:/ci/requests_1657717096906/work
requests-oauthlib==1.3.1
rfc3339-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1638811747357/work
rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
rich==13.3.5
rsa==4.9
scikit-image==0.20.0
scikit-learn @ file:///D:/bld/scikit-learn_1652976994170/work
scipy==1.9.1
seaborn==0.12.2
Send2Trash @ file:///D:/bld/send2trash_1682601429724/work
sentry-sdk==1.23.1
setproctitle==1.3.2
shellingham==1.5.0.post1
SimpleITK==2.2.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smmap==5.0.0
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
snowballstemmer==2.2.0
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1658207591808/work
Sphinx==4.5.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
SQLAlchemy==2.0.15
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
superqt==0.4.1
sympy==1.12
tabulate @ file:///home/conda/feedstock_root/build_artifacts/tabulate_1665138452165/work
tensorboard==2.13.0
tensorboard-data-server==0.7.0
terminado @ file:///D:/bld/terminado_1652790770644/work
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
tifffile==2023.4.12
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1666100256010/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///C:/Windows/TEMP/abs_ac109f85-a7b3-4b4d-bcfd-52622eceddf0hy332ojo/croots/recipe/tomli_1657175513137/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
torch==1.8.1
torchio==0.18.91
torchvision==0.9.1
tornado==6.3.2
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
typer==0.9.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1678559861143/work
tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1680081134351/work
urllib3==1.26.15
vispy==0.11.0
wandb==0.15.3
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1684708148666/work
Werkzeug==2.3.4
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1680021576815/work
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306167264/work
win32-setctime @ file:///home/conda/feedstock_root/build_artifacts/win32_setctime_1642883564726/work
wrapt==1.15.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1677313463193/work

```

Any help getting this sorted would be greatly appreciated!!

All the best,

Michael

**Comment by kanishk16** [comment]
Hey Michael @GrimmSnark, 

Sorry for not getting back to you sooner. We identified a bug due to upstream changes in `imageio`, but the good news is we have a fix in place.

Once #1297 lands, I'd suggest creating a fresh conda environment and installing ivadomed from master as:
```
python -m pip install --upgrade pip

git clone -q https://github.com/ivadomed/ivadomed.git

cd ivadomed

python -m pip install -q -e .[dev]

python -m pip install --upgrade imageio
```
If #1297 takes some time to land in the master branch feel free to either copy the changes from it in your local version or checkout that branch to get the changes **before installing**:

```
git checkout kk/chore_imageio
```
Your updated workflow might look something like this: 
```
python -m pip install --upgrade pip

git clone -q https://github.com/ivadomed/ivadomed.git

cd ivadomed

git checkout kk/chore_imageio

python -m pip install -q -e .[dev]

python -m pip install --upgrade imageio
```
Now, you'd be good to go!

Since windows follow `\` (backward slash), notice this in your prompt:
```
(axondeepsegEnv1) D:\Data\ivadomedTest\data_axondeepseg_sem>
```
Hence, your `path_output` in the config should look something along the lines:
```
"path_output": "D:\\Data\\ivadomedTest\\data_axondeepseg_sem\\output",
```
This also applies to any path you specify in the config file, such as `path_data` or `bids_config`...

Let us know if this doesn't resolve your issue. We'd be happy to help.

**Comment by GrimmSnark** [comment]
Hello @kanishk16 

Thank you for getting back to me. That seems to have solved the issue and I am getting to training an network at the moment! I'll probably bug you all again later once I get further down the path.

Thanks again,

Michael
