### ISSUE TITLE
BIDS parsing error for ADS user on Windows

### ISSUE THREAD

**Issue by mathieuboudreau** [ivadomed/ivadomed#1295]
We have a user over at AxonDeepSeg that just opened an issue, and I think it has to do with the BIDS parser here on IVADOMED. https://github.com/axondeepseg/axondeepseg/issues/743

Here is his session log:

```
(axondeepsegEnv1) D:\Data\ivadomedTest\data_axondeepseg_sem>ivadomed -c config_microscopy.json
2023-06-02 11:54:32.318 | INFO     | ivadomed.utils:init_ivadomed:454 -
ivadomed (2.9.7)

2023-06-02 11:54:32.321 | INFO     | ivadomed.config_manager:_display_differing_keys:153 - Adding the following keys to the configuration file
2023-06-02 11:54:32.322 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     log_file: log
2023-06-02 11:54:32.322 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     loader_parameters: is_input_dropout: False
2023-06-02 11:54:32.323 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     lr_scheduler: base_lr: 1e-05
2023-06-02 11:54:32.323 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     lr_scheduler: max_lr: 0.01
2023-06-02 11:54:32.323 | INFO     | ivadomed.config_manager:deep_dict_compare:44 -     uncertainty: {'epistemic': False, 'aleatoric': False, 'n_it': 0}
2023-06-02 11:54:32.324 | INFO     | ivadomed.config_manager:_display_differing_keys:155 -

2023-06-02 11:54:32.325 | INFO     | ivadomed.utils:get_command:387 - No CLI argument given for command: ( --train | --test | --segment ). Will check config file for command...
2023-06-02 11:54:32.325 | INFO     | ivadomed.utils:get_path_output:404 - CLI flag --path-output not used to specify output directory. Will check config file for directory...
2023-06-02 11:54:32.326 | INFO     | ivadomed.utils:get_path_data:417 - CLI flag --path-data not used to specify BIDS data directory. Will check config file for directory...
2023-06-02 11:54:32.327 | INFO     | ivadomed.main:set_output_path:215 - Output path already exists: D:/Data/ivadomedTest/data_axondeepseg_sem/output
2023-06-02 11:54:32.390 | INFO     | ivadomed.utils:define_device:160 - Cuda is not available.
2023-06-02 11:54:32.391 | INFO     | ivadomed.utils:define_device:161 - Working on cpu.
2023-06-02 11:54:32.392 | INFO     | ivadomed.utils:display_selected_model_spec:176 - Selected architecture: Unet, with the following parameters:
2023-06-02 11:54:32.394 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   dropout_rate: 0.2
2023-06-02 11:54:32.394 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   bn_momentum: 0.1
2023-06-02 11:54:32.395 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   depth: 4
2023-06-02 11:54:32.395 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   is_2d: True
2023-06-02 11:54:32.396 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   final_activation: sigmoid
2023-06-02 11:54:32.396 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   length_2D: [256, 256]
2023-06-02 11:54:32.397 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   stride_2D: [244, 244]
2023-06-02 11:54:32.397 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   folder_name: model_seg_rat_axon-myelin_sem
2023-06-02 11:54:32.398 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   in_channel: 1
2023-06-02 11:54:32.399 | INFO     | ivadomed.utils:display_selected_model_spec:179 -   out_channel: 3
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\Scripts\ivadomed.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\ivadomed\main.py", line 623, in run_main
    run_command(context=context,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\ivadomed\main.py", line 398, in run_command
    bids_df = BidsDataframe(loader_params, path_output, derivatives=True,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\ivadomed\loader\bids_dataframe.py", line 72, in __init__
    self.create_bids_dataframe()
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\ivadomed\loader\bids_dataframe.py", line 113, in create_bids_dataframe
    layout = pybids.BIDSLayout(str(path_data), config=self.bids_config, indexer=indexer,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\bids\layout\layout.py", line 176, in __init__
    indexer(self)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\bids\layout\index.py", line 141, in __call__
    self._include_patterns = [
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\bids\layout\index.py", line 142, in <listcomp>
    _regexfy(patt, root=self._layout._root) for patt in listify(force)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\site-packages\bids\layout\index.py", line 28, in _regexfy
    return re.compile(r"^/" + str(patt) + r".*")
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\re.py", line 252, in compile
    return _compile(pattern, flags)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_parse.py", line 525, in _parse
    code = _escape(source, this, state)
  File "C:\ProgramData\anaconda3\envs\axondeepsegEnv1\lib\sre_parse.py", line 426, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \m at position 10

(axondeepsegEnv1) D:\Data\ivadomedTest\data_axondeepseg_sem>
```

The user indicated that they're using Windows also, and I know that could cause an issue regarding how paths are dealt (i.e. if `Path()` isn't strictly used in IVADOMED (in particular, in the line where it does this conversion, `str(path_data)` in the log above, it may not convert properly the filepaths if the filepath wasn't ceated using `Path()`)

Anyone here (or even @mariehbourget) with some insights that could help our user, would be appreciated!

Thanks!

**Comment by kanishk16** [comment]
Closing as resolved in the original issue opened by user #1294
