### ISSUE TITLE
ivadomed_segment_image RuntimeError: 'PixelSizeUnits' is missing from metadata

### ISSUE THREAD

**Issue by GrimmSnark** [ivadomed/ivadomed#1302]
### Current behavior

Hello,

So I am trying to apply a newly trained model to some new images. When I try to run the following command line argument

```
(ads_venv) E:\Data\mouse\ivadomed\test2>ivadomed_segment_image -i E:\Data\mouse\ivadomed\segment\20230220\imSeq\MAX_P6_ret1_cluster1_microglia_IB4_694_cntrl_cleaned_C10000.tif -m E:\Data\mouse\ivadomed\test2\testModel\testModel_1
```

 I get the below error:

```
2023-08-16 17:18:47.304 | INFO     | ivadomed.utils:init_ivadomed:466 -
ivadomed (2.9.8)

2023-08-16 17:18:47.331 | INFO     | ivadomed.utils:define_device:178 - Using GPU ID 0
2023-08-16 17:18:47.346 | INFO     | ivadomed.config_manager:_display_differing_keys:202 - Adding the following keys to the configuration file
2023-08-16 17:18:47.347 | INFO     | ivadomed.config_manager:_display_differing_keys:204 -

2023-08-16 17:18:47.350 | WARNING  | ivadomed.inference:segment_volume:411 - fname_roi has not been specified, then the entire volume is processed.
Lossy conversion from uint16 to uint8. Losing 8 bits of resolution. Convert image to uint8 prior to saving to suppress this warning.
Traceback (most recent call last):
  File "\\?\D:\Anaconda\envs\ads_venv\Scripts\ivadomed_segment_image-script.py", line 33, in <module>
    sys.exit(load_entry_point('ivadomed', 'console_scripts', 'ivadomed_segment_image')())
  File "d:\pythonpackages\ivadomed\ivadomed\scripts\segment_image.py", line 108, in main
    segment_image(args.image, args.model, args.suffix, options)
  File "d:\pythonpackages\ivadomed\ivadomed\scripts\segment_image.py", line 86, in segment_image
    nii_lst, target_lst = imed_inference.segment_volume(path_model, fname_images, options=options)
  File "d:\pythonpackages\ivadomed\ivadomed\inference.py", line 484, in segment_volume
    ds.load_filenames()
  File "d:\pythonpackages\ivadomed\ivadomed\loader\mri2d_segmentation_dataset.py", line 127, in load_filenames
    roi_pair = SegmentationPair(input_filenames,
  File "d:\pythonpackages\ivadomed\ivadomed\loader\segmentation_pair.py", line 59, in __init__
    input_img = self.read_file(input_file)
  File "d:\pythonpackages\ivadomed\ivadomed\loader\segmentation_pair.py", line 297, in read_file
    img = self.convert_file_to_nifti(filename, extension, is_gt)
  File "d:\pythonpackages\ivadomed\ivadomed\loader\segmentation_pair.py", line 334, in convert_file_to_nifti
    ps_in_mm = self.get_microscopy_pixelsize(filename)
  File "d:\pythonpackages\ivadomed\ivadomed\loader\segmentation_pair.py", line 379, in get_microscopy_pixelsize
    raise RuntimeError("'PixelSizeUnits' is missing from metadata")
RuntimeError: 'PixelSizeUnits' is missing from metadata
```
Any help would be greatly appreciated!
### System description

Anaconda running on Windows 10

### Installed packages

<details open>
<summary> Output of <code>pip freeze</code> </summary>

```
absl-py==1.4.0
alabaster==0.7.13
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1685486400275/work/dist
apeye==1.4.0
apeye-core==1.1.4
app-model==0.1.4
appdirs==1.4.4
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///D:/bld/argon2-cffi-bindings_1666850778155/work
astor==0.8.1
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
atomicwrites==1.4.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work
autodocsumm==0.2.11
-e git+https://github.com/neuropoly/axondeepseg.git@a5482ded656d3fd9e830385c218239adef631f35#egg=AxonDeepSeg
Babel==2.12.1
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1687772187254/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1680888073205/work
bids-validator==1.11.0
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1674535352125/work
Brotli @ file:///D:/bld/brotli-split_1687884251065/work
build==0.10.0
CacheControl==0.13.1
cachetools==5.3.1
cachey==0.2.1
certifi @ file:///C:/b/abs_4a0polqwty/croot/certifi_1683875377622/work/certifi
cffi @ file:///D:/bld/cffi_1671179504620/work
cfgv==3.3.1
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1678108872112/work
click @ file:///D:/bld/click_1666798499870/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1674202310934/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
coloredlogs==15.0.1
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1679481329611/work
consolekit==1.4.1
contextlib2 @ file:///home/conda/feedstock_root/build_artifacts/contextlib2_1624848568296/work
contourpy @ file:///D:/bld/contourpy_1686733973830/work
coverage==6.5.0
coveralls==3.3.1
cssutils==2.7.1
csv-diff==1.1
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
cytoolz @ file:///D:/bld/cytoolz_1666829685547/work
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1683908660643/work
debugpy @ file:///D:/bld/debugpy_1680755540111/work
decopatch==1.4.10
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
Deprecated==1.2.14
deprecation==2.1.0
deprecation-alias==0.3.2
dict2css==0.3.0
dictdiffer==0.9.0
distlib==0.3.6
docker-pycreds==0.4.0
docopt==0.6.2
docstring-parser==0.15
docutils==0.16
domdf-python-tools==3.6.1
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
et-xmlfile @ file:///home/conda/feedstock_root/build_artifacts/et_xmlfile_1674664118162/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1678703645500/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1684761244589/work/dist
filelock==3.12.2
flake8==6.0.0
flatbuffers==23.5.26
flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1684084314667/work/source/flit_core
fonttools @ file:///D:/bld/fonttools_1686578668379/work
formulaic==0.5.2
freetype-py==2.4.0
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1686342280219/work
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.21.0
google-auth-oauthlib==1.0.0
graphlib-backport==1.0.3
greenlet==2.0.2
grpcio==1.56.0
h5py @ file:///D:/bld/h5py_1617739735319/work
HeapDict==1.0.1
hsluv==5.0.3
html5lib==1.1
humanfriendly==10.0
humanize==4.7.0
identify==2.5.24
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
imagecodecs @ file:///D:/bld/imagecodecs_1679699829332/work
imageio==2.31.1
imagesize==1.4.1
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1687138353019/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1676919000169/work
in-n-out==0.1.7
iniconfig @ file:///home/conda/feedstock_root/build_artifacts/iniconfig_1673103042956/work
interface-meta==1.3.0
ipykernel @ file:///D:/bld/ipykernel_1687739194036/work
ipython @ file:///D:/bld/ipython_1683289169355/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1680023138361/work
-e git+https://github.com/ivadomed/ivadomed.git@d6769d2fda4cf7f38a1aa2219a803fd71e31b803#egg=ivadomed
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1687965927691/work
jsonpointer==2.4
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1669810440410/work
jupyter @ file:///D:/bld/jupyter_1670249824040/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1678118109161/work
jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/jupyter_events_1673559782596/work
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1687700988094/work
jupyter_core @ file:///D:/bld/jupyter_core_1686775775850/work
jupyter_server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1687869799272/work
jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1673491454549/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649936611996/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1684239754370/work
kiwisolver @ file:///D:/bld/kiwisolver_1666805810106/work
locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
lockfile==0.12.2
loguru==0.7.0
magicgui==0.7.2
makefun==1.15.1
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe @ file:///D:/bld/markupsafe_1685769190245/work
matplotlib @ file:///D:/bld/matplotlib-suite_1678135709170/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mccabe==0.7.0
mdurl==0.1.2
mistletoe==1.1.0
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1686313613819/work/dist
mpld3 @ file:///home/conda/feedstock_root/build_artifacts/mpld3_1670691928456/work
mpmath==1.3.0
msgpack==1.0.5
munkres==1.1.4
mypy-extensions==1.0.0
napari==0.4.17
napari-ADS @ file:///D:/pythonPackages/axondeepseg/plugins
napari-console==0.0.8
napari-plugin-engine==0.2.0
napari-svg==0.1.10
natsort==8.4.0
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1683202081046/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1684790896106/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1687202153002/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1685541374434/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1680692919326/work
nibabel @ file:///home/conda/feedstock_root/build_artifacts/nibabel_1644264968592/work
nodeenv==1.8.0
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1680870634737/work
notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1682360583588/work
npe2==0.7.0
num2words==0.5.12
numpy @ file:///D:/bld/numpy_1687808486521/work
numpydoc==1.5.0
oauthlib==3.2.2
onnxruntime==1.15.1
openpyxl @ file:///D:/bld/openpyxl_1682610949304/work
overrides @ file:///home/conda/feedstock_root/build_artifacts/overrides_1666057828264/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==1.4.4
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1681246756246/work
pathtools==0.1.2
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///D:/bld/pillow_1684654185064/work
Pint==0.21.1
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1687705014305/work
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1687776318736/work
ply==3.11
pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1679580333621/work
pre-commit==3.3.3
prettytable @ file:///home/conda/feedstock_root/build_artifacts/prettytable_1681201605171/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1684970902412/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
protobuf==3.20.1
psutil @ file:///D:/bld/psutil_1681775153467/work
psygnal==0.9.1
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
py==1.11.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pybids==0.16.1
pycodestyle==2.10.0
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydantic==1.10.9
pydicom @ file:///home/conda/feedstock_root/build_artifacts/pydicom_1687180064324/work
pyflakes==3.0.1
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
PyOpenGL==3.1.7
pypandoc==1.11
pyparsing==2.4.7
pyproject_hooks==1.0.0
PyQt5==5.15.7
PyQt5-sip @ file:///D:/bld/pyqt-split_1674666773953/work/pyqt_sip
pyreadline @ file:///D:/bld/pyreadline_1667055513906/work
pyreadline3==3.4.1
pyrsistent @ file:///D:/bld/pyrsistent_1672681635682/work
PySocks @ file:///D:/bld/pysocks_1661604991356/work
pytest==6.2.5
pytest-cases==3.6.14
pytest-console-scripts==1.4.1
pytest-cov @ file:///home/conda/feedstock_root/build_artifacts/pytest-cov_1684964868191/work
pytest-ordering==0.6
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1677079630776/work
pytomlpp==1.0.13
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
PyWavelets @ file:///D:/bld/pywavelets_1673082529577/work
pywin32==304
pywinpty @ file:///D:/bld/pywinpty_1672753227989/work/target/wheels/pywinpty-2.0.10-cp38-none-win_amd64.whl
PyYAML @ file:///D:/bld/pyyaml_1666772539683/work
pyzmq @ file:///D:/bld/pyzmq_1685519494070/work
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole-base_1678686825741/work
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1680148448366/work
raven==6.10.0
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
requests-oauthlib==1.3.1
rfc3339-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1638811747357/work
rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
rich==13.4.2
rsa==4.9
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
scikit-image @ file:///D:/bld/scikit-image_1667117378202/work
scikit-learn @ file:///D:/bld/scikit-learn_1652976994170/work
scipy==1.10.1
seaborn==0.12.2
Send2Trash @ file:///D:/bld/send2trash_1682601429724/work
sentry-sdk==1.26.0
setproctitle==1.3.2
shellingham==1.5.0.post1
SimpleITK==2.2.1
sip @ file:///D:/bld/sip_1681995199960/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smmap==5.0.0
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
snowballstemmer==2.2.0
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1658207591808/work
Sphinx==4.3.2
sphinx-autodoc-typehints==1.11.1
sphinx-jsonschema==1.19.1
sphinx-prompt==1.5.0
sphinx-rtd-theme==1.2.2
sphinx-tabs==3.2.0
sphinx-toolbox==2.15.2
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
SQLAlchemy==2.0.17
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
superqt==0.4.1
sympy==1.12
tabulate @ file:///home/conda/feedstock_root/build_artifacts/tabulate_1665138452165/work
tensorboard==2.13.0
tensorboard-data-server==0.7.1
terminado @ file:///D:/bld/terminado_1666707934477/work
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1681364231336/work
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1666100256010/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
torch==1.11.0+cu113
torchio==0.18.92
torchvision==0.12.0+cu113
tornado @ file:///D:/bld/tornado_1684150225285/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
typer==0.9.0
typing-utils @ file:///home/conda/feedstock_root/build_artifacts/typing_utils_1622899189314/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1687998981955/work
tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1680081134351/work
unicodedata2 @ file:///D:/bld/unicodedata2_1667240053339/work
urllib3==1.26.16
virtualenv==20.23.1
vispy==0.11.0
wandb==0.15.4
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1687789148259/work
Werkzeug==2.3.6
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1680021576815/work
win-inet-pton @ file:///D:/bld/win_inet_pton_1667051142467/work
win32-setctime==1.1.0
wrapt==1.15.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1677313463193/work
```

</details>

**Comment by GrimmSnark** [comment]
Perfect, thank you very much for your response!
