### ISSUE TITLE
Hi, I encounter an issue: 'RuntimeError: Derivatives not found.'

### ISSUE THREAD

**Issue by zwb0** [ivadomed/ivadomed#1305]
Hi, I'm running the first tutorial. But I encounter the issue below,

> (ivadomed_env) root@7kmbka3tn7gbj-0:/218019046/ivadomed# ivadomed --train -c /218019046/ivadomed/ivadomed/config/config.json --path-data /218019046/ivadomed/data_example_spinegeneric --path-output /218019046/ivadomed/output/
> 
> 2023-11-17 10:07:53.044 | INFO     | ivadomed.utils:init_ivadomed:454 -
> ivadomed (2.9.8)
> 
> 2023-11-17 10:07:53.053 | INFO     | ivadomed.main:set_output_path:215 - Output path already exists: /218019046/ivadomed/output/
> 2023-11-17 10:07:53.615 | INFO     | ivadomed.utils:define_device:166 - Using GPU ID 0
> 2023-11-17 10:07:53.617 | INFO     | ivadomed.utils:display_selected_model_spec:176 - Selected architecture: Unet, with the following parameters:
> 2023-11-17 10:07:53.618 | INFO     | ivadomed.utils:display_selected_model_spec:179 - 	dropout_rate: 0.3
> 2023-11-17 10:07:53.619 | INFO     | ivadomed.utils:display_selected_model_spec:179 - 	bn_momentum: 0.1
> 2023-11-17 10:07:53.620 | INFO     | ivadomed.utils:display_selected_model_spec:179 - 	depth: 3
> 2023-11-17 10:07:53.622 | INFO     | ivadomed.utils:display_selected_model_spec:179 - 	is_2d: True
> 2023-11-17 10:07:53.623 | INFO     | ivadomed.utils:display_selected_model_spec:179 - 	final_activation: sigmoid
> 2023-11-17 10:07:53.624 | INFO     | ivadomed.utils:display_selected_model_spec:179 - 	folder_name: my_model
> 2023-11-17 10:07:53.626 | INFO     | ivadomed.utils:display_selected_model_spec:179 - 	in_channel: 1
> 2023-11-17 10:07:53.626 | INFO     | ivadomed.utils:display_selected_model_spec:179 - 	out_channel: 1
> 2023-11-17 10:07:54.800 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-cardiff03_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.800 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-cardiff03_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.801 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-cardiff03_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.802 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-hamburg01_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.803 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-hamburg01_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.803 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-juntendo750w01_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.804 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-juntendo750w01_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.805 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-juntendo750w01_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.805 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-mpicbs06_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.806 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-mpicbs06_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.806 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-mpicbs06_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.808 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-oxfordFmrib07_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.808 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-oxfordFmrib07_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.809 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-oxfordFmrib07_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.809 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-oxfordFmrib11_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.810 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-oxfordFmrib11_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.811 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-oxfordFmrib11_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.812 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-sapienza05_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.812 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-sapienza05_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.813 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-sapienza05_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.814 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-strasbourg04_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.814 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-strasbourg04_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.815 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-strasbourg04_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.816 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-tokyoSkyra06_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.817 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-tokyoSkyra06_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.817 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-tokyoSkyra06_T2w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.818 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-unf01_T1w.nii.gz. Skipping file.
> 2023-11-17 10:07:54.818 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-unf01_T2star.nii.gz. Skipping file.
> 2023-11-17 10:07:54.819 | WARNING  | ivadomed.loader.bids_dataframe:get_subjects_with_derivatives:278 - Missing derivatives for sub-unf01_T2w.nii.gz. Skipping file.
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/ivadomed_env/bin/ivadomed", line 8, in <module>
>     sys.exit(run_main())
>   File "/root/miniconda3/envs/ivadomed_env/lib/python3.8/site-packages/ivadomed/main.py", line 623, in run_main
>     run_command(context=context,
>   File "/root/miniconda3/envs/ivadomed_env/lib/python3.8/site-packages/ivadomed/main.py", line 398, in run_command
>     bids_df = BidsDataframe(loader_params, path_output, derivatives=True,
>   File "/root/miniconda3/envs/ivadomed_env/lib/python3.8/site-packages/ivadomed/loader/bids_dataframe.py", line 72, in __init__
>     self.create_bids_dataframe()
>   File "/root/miniconda3/envs/ivadomed_env/lib/python3.8/site-packages/ivadomed/loader/bids_dataframe.py", line 183, in create_bids_dataframe
>     raise RuntimeError("Derivatives not found.")
> RuntimeError: Derivatives not found.

I have no idea why the derivatives can not be found. Thanks a lot if you give me some hints

**Comment by kanishk16** [comment]
Hi @zwb0,

Thanks for reaching out. We're aware of the above issue. It is due to upstream changes in `pybids` and we're investigating to find a long-term fix to this, but meanwhile, a hacky approach would be to set the `bids_validate` key to `false` under the `loader_parameters` in the `config.json`. Thus your `config.json` might look something like:
```
{
    "command": "train",
    
      ...
      
     "loader_parameters": {
        "path_data": ["data_example_spinegeneric"],
         ...
        "bids_validate": false
    },

}
```

**Comment by joshuacwnewton** [comment]
This has addressed on `master` by restricting PyBIDS to an earlier version:

https://github.com/ivadomed/ivadomed/blob/de2bb2097263f0cd9c3ca58eeebdcaa3d79c4ef8/requirements.txt#L20

Ideally, though, we would update ivadomed to be compatible with the newest versions of PyBIDS, so I'll leave this issue open. :)
