### ISSUE TITLE
Uncertainty quantification is not robust to 4D inputs

### ISSUE THREAD

**Issue by lrouhier** [ivadomed/ivadomed#369]
Uncertinty is computes on a single 3D, however the output is (H,W,D,C) now to accomodate for multichannel. This does not seem to work anymore and needs to be fixed. By looping over the channels it should be possible to make it work on multichannel/multilabel images as well.

**Comment by lrouhier** [comment]
~~~
Loading dataset: 100%|██████████| 2/2 [00:00<00:00, 1545.15it/s]
Inference - Iteration 0: 100%|██████████| 5/5 [00:11<00:00,  2.35s/it]
Inference - Iteration 1: 100%|██████████| 5/5 [00:08<00:00,  1.75s/it]
Uncertainty Computation:   0%|          | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/luroub/anaconda3/envs/conda-37/bin/ivadomed", line 11, in <module>
    load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
  File "/home/GRAMES.POLYMTL.CA/luroub/clean/visualize_fix/ivadomed/ivadomed/main.py", line 284, in run_main
    thr_increment=args.thr_increment if args.thr_increment else None)
  File "/home/GRAMES.POLYMTL.CA/luroub/clean/visualize_fix/ivadomed/ivadomed/main.py", line 248, in run_command
    metric_fns=metric_fns)
  File "/home/GRAMES.POLYMTL.CA/luroub/clean/visualize_fix/ivadomed/ivadomed/testing.py", line 75, in test
    imed_utils.run_uncertainty(ifolder=path_3Dpred)
  File "/home/GRAMES.POLYMTL.CA/luroub/clean/visualize_fix/ivadomed/ivadomed/utils.py", line 140, in run_uncertainty
    structurewise_uncertainty(fname_pred_lst, fname_pred, fname_unc_vox, fname_unc_struct)
  File "/home/GRAMES.POLYMTL.CA/luroub/clean/visualize_fix/ivadomed/ivadomed/utils.py", line 223, in structurewise_uncertainty
    data_hard_l, n_l = label(data_hard, structure=bin_struct)
  File "/home/GRAMES.POLYMTL.CA/luroub/anaconda3/envs/conda-37/lib/python3.7/site-packages/scipy/ndimage/measurements.py", line 186, in label
    raise RuntimeError('structure and input must have equal rank')
RuntimeError: structure and input must have equal rank
~~~
