### ISSUE TITLE
ivadomed not useable on fresh wheels install

### ISSUE THREAD

**Issue by Drulex** [ivadomed/ivadomed#487]
I stumbled upon this while investigating something else related to `spinalcordtoolbox`. Attempting to import `ivadomed` on a fresh wheel install fails due to `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/ivadomed/version.txt'`

<details>
  <summary>Detailed error log</summary>

```
$ docker run --interactive --tty --entrypoint /bin/bash --net=host python:3.6
root@drupad-p1:/# pip install ivadomed
Collecting ivadomed
  Downloading ivadomed-2.3.1-py3-none-any.whl (129 kB)
     |████████████████████████████████| 129 kB 625 kB/s
Collecting joblib
  Downloading joblib-0.17.0-py3-none-any.whl (301 kB)
     |████████████████████████████████| 301 kB 556 kB/s
Collecting torch>=1.5.0
  Downloading torch-1.6.0-cp36-cp36m-manylinux1_x86_64.whl (748.8 MB)
     |████████████████████████████████| 748.8 MB 6.5 kB/s
Collecting pillow>=7.0.0
  Downloading Pillow-8.0.1-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 27.6 MB/s
Collecting bids-neuropoly>=0.2
  Downloading bids_neuropoly-0.2-py3-none-any.whl (3.1 kB)
Collecting pytest
  Downloading pytest-6.1.1-py3-none-any.whl (272 kB)
     |████████████████████████████████| 272 kB 14.0 MB/s
Collecting matplotlib>=3.3.0
  Downloading matplotlib-3.3.2-cp36-cp36m-manylinux1_x86_64.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 12.6 MB/s
Collecting nibabel
  Downloading nibabel-3.2.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 16.4 MB/s
Collecting scikit-learn>=0.20.3
  Downloading scikit_learn-0.23.2-cp36-cp36m-manylinux1_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 18.3 MB/s
Collecting pandas
  Downloading pandas-1.1.3-cp36-cp36m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 19.2 MB/s
Collecting scikit-image
  Downloading scikit_image-0.17.2-cp36-cp36m-manylinux1_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 294 kB/s
Collecting tensorboard
  Downloading tensorboard-2.3.0-py3-none-any.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 21.8 MB/s
Collecting torchvision>=0.6.0
  Downloading torchvision-0.7.0-cp36-cp36m-manylinux1_x86_64.whl (5.9 MB)
     |████████████████████████████████| 5.9 MB 20.0 MB/s
Collecting tqdm>=4.30
  Downloading tqdm-4.51.0-py2.py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 5.7 MB/s
Collecting h5py
  Downloading h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 22.8 MB/s
Collecting onnxruntime
  Downloading onnxruntime-1.5.2-cp36-cp36m-manylinux2014_x86_64.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 27.1 MB/s
Collecting seaborn
  Downloading seaborn-0.11.0-py3-none-any.whl (283 kB)
     |████████████████████████████████| 283 kB 21.0 MB/s
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 24.2 MB/s
Collecting numpy
  Downloading numpy-1.19.2-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 28.7 MB/s
Collecting pybids>=0.6.5
  Downloading pybids-0.12.3-py2.py3-none-any.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 27.3 MB/s
Collecting toml
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting attrs>=17.4.0
  Downloading attrs-20.2.0-py2.py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 2.5 MB/s
Collecting py>=1.8.2
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
     |████████████████████████████████| 99 kB 5.0 MB/s
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 28.4 MB/s
Collecting certifi>=2020.06.20
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 19.8 MB/s
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 3.1 MB/s
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (88 kB)
     |████████████████████████████████| 88 kB 4.9 MB/s
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting scipy>=0.19.1
  Downloading scipy-1.5.3-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 17.5 MB/s
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 31.3 MB/s
Collecting networkx>=2.0
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 28.5 MB/s
Collecting imageio>=2.3.0
  Downloading imageio-2.9.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 23.5 MB/s
Collecting tifffile>=2019.7.26
  Downloading tifffile-2020.9.3-py3-none-any.whl (148 kB)
     |████████████████████████████████| 148 kB 41.7 MB/s
Collecting PyWavelets>=1.1.1
  Downloading PyWavelets-1.1.1-cp36-cp36m-manylinux1_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 39.0 MB/s
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/site-packages (from tensorboard->ivadomed) (50.3.0)
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.22.1-py2.py3-none-any.whl (114 kB)
     |████████████████████████████████| 114 kB 35.6 MB/s
Collecting grpcio>=1.24.3
  Downloading grpcio-1.33.1-cp36-cp36m-manylinux2014_x86_64.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 37.1 MB/s
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 4.5 MB/s
Collecting werkzeug>=0.11.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 25.3 MB/s
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779 kB)
     |████████████████████████████████| 779 kB 30.3 MB/s
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /usr/local/lib/python3.6/site-packages (from tensorboard->ivadomed) (0.35.1)
Collecting protobuf>=3.6.0
  Downloading protobuf-3.13.0-cp36-cp36m-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 15.8 MB/s
Collecting six>=1.10.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting requests<3,>=2.21.0
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 259 kB/s
Collecting absl-py>=0.4
  Downloading absl_py-0.10.0-py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 28.3 MB/s
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 654 kB/s
Collecting sqlalchemy
  Downloading SQLAlchemy-1.3.20-cp36-cp36m-manylinux2010_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 43.4 MB/s
Collecting bids-validator
  Downloading bids_validator-1.5.7-py2.py3-none-any.whl (15 kB)
Collecting num2words
  Downloading num2words-0.5.10-py3-none-any.whl (101 kB)
     |████████████████████████████████| 101 kB 6.8 MB/s
Collecting patsy
  Downloading patsy-0.5.1-py2.py3-none-any.whl (231 kB)
     |████████████████████████████████| 231 kB 28.4 MB/s
Collecting zipp>=0.5
  Downloading zipp-3.4.0-py3-none-any.whl (5.2 kB)
Collecting decorator>=4.3.0
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.5"
  Downloading rsa-4.6-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 3.3 MB/s
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 22.6 MB/s
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 6.8 MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 25.6 MB/s
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 31.4 MB/s
Collecting docopt>=0.6.2
  Downloading docopt-0.6.2.tar.gz (25 kB)
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 3.2 MB/s
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 34.8 MB/s
Building wheels for collected packages: future, docopt
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=c1e24d8315d0e55bedae2a3c76ded7824d475e697472ea9258bd488559526761
  Stored in directory: /root/.cache/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13704 sha256=bb80ab6f6cf24f56014e284650644f4b0fd1c36eb83a8fa340dd07cbe10ba1f6
  Stored in directory: /root/.cache/pip/wheels/3f/2a/fa/4d7a888e69774d5e6e855d190a8a51b357d77cc05eb1c097c9
Successfully built future docopt
Installing collected packages: joblib, future, numpy, torch, pillow, six, pyparsing, packaging, nibabel, pytz, python-dateutil, pandas, click, sqlalchemy, scipy, bids-validator, docopt, num2words, patsy, pybids, bids-neuropoly, toml, zipp, importlib-metadata, pluggy, iniconfig, attrs, py, pytest, certifi, cycler, kiwisolver, matplotlib, threadpoolctl, scikit-learn, decorator, networkx, imageio, tifffile, PyWavelets, scikit-image, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, grpcio, markdown, werkzeug, tensorboard-plugin-wit, idna, urllib3, chardet, requests, oauthlib, requests-oauthlib, google-auth-oauthlib, protobuf, absl-py, tensorboard, torchvision, tqdm, h5py, onnxruntime, seaborn, ivadomed
Successfully installed PyWavelets-1.1.1 absl-py-0.10.0 attrs-20.2.0 bids-neuropoly-0.2 bids-validator-1.5.7 cachetools-4.1.1 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 cycler-0.10.0 decorator-4.4.2 docopt-0.6.2 future-0.18.2 google-auth-1.22.1 google-auth-oauthlib-0.4.1 grpcio-1.33.1 h5py-2.10.0 idna-2.10 imageio-2.9.0 importlib-metadata-2.0.0 iniconfig-1.1.1 ivadomed-2.3.1 joblib-0.17.0 kiwisolver-1.2.0 markdown-3.3.3 matplotlib-3.3.2 networkx-2.5 nibabel-3.2.0 num2words-0.5.10 numpy-1.19.2 oauthlib-3.1.0 onnxruntime-1.5.2 packaging-20.4 pandas-1.1.3 patsy-0.5.1 pillow-8.0.1 pluggy-0.13.1 protobuf-3.13.0 py-1.9.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pybids-0.12.3 pyparsing-2.4.7 pytest-6.1.1 python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0 requests-oauthlib-1.3.0 rsa-4.6 scikit-image-0.17.2 scikit-learn-0.23.2 scipy-1.5.3 seaborn-0.11.0 six-1.15.0 sqlalchemy-1.3.20 tensorboard-2.3.0 tensorboard-plugin-wit-1.7.0 threadpoolctl-2.1.0 tifffile-2020.9.3 toml-0.10.1 torch-1.6.0 torchvision-0.7.0 tqdm-4.51.0 urllib3-1.25.11 werkzeug-1.0.1 zipp-3.4.0
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

root@drupad-p1:/# ivadomed -h
Traceback (most recent call last):
  File "/usr/local/bin/ivadomed", line 5, in <module>
    from ivadomed.main import run_main
  File "/usr/local/lib/python3.6/site-packages/ivadomed/__init__.py", line 1, in <module>
    from .utils import __version__, __ivadomed_dir__
  File "/usr/local/lib/python3.6/site-packages/ivadomed/utils.py", line 1215, in <module>
    __version__ = _version_string()
  File "/usr/local/lib/python3.6/site-packages/ivadomed/utils.py", line 1207, in _version_string
    install_type, ivadomed_commit, ivadomed_branch, version_ivadomed = _git_info()
  File "/usr/local/lib/python3.6/site-packages/ivadomed/utils.py", line 1118, in _git_info
    with open(path_version) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/ivadomed/version.txt'

root@drupad-p1:/# python
Python 3.6.12 (default, Sep 10 2020, 17:53:20)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ivadomed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ivadomed/__init__.py", line 1, in <module>
    from .utils import __version__, __ivadomed_dir__
  File "/usr/local/lib/python3.6/site-packages/ivadomed/utils.py", line 1215, in <module>
    __version__ = _version_string()
  File "/usr/local/lib/python3.6/site-packages/ivadomed/utils.py", line 1207, in _version_string
    install_type, ivadomed_commit, ivadomed_branch, version_ivadomed = _git_info()
  File "/usr/local/lib/python3.6/site-packages/ivadomed/utils.py", line 1118, in _git_info
    with open(path_version) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/ivadomed/version.txt'
```
</details>

This does not occur when performing a development install (`git clone` + `pip install -r requirements.txt` + `pip install -e .`). 

I suspect it has to do with `version.txt` not being copied over by the `setup.py` when creating the wheel. Probably just need to add it to the `MANIFEST.in`.

**Comment by jcohenadad** [comment]
For additional context, this behaviour was likely introduced in https://github.com/ivadomed/ivadomed/pull/481 

Thank you for catching and reporting this @Drulex
