### ISSUE TITLE
Error on fresh installation of ivadomed on Rosenberg

### ISSUE THREAD

**Issue by mpompolas** [ivadomed/ivadomed#526]
ivadomed                2.5.0               /home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages pip

u111358@rosenberg:~/data_nvme_u111358$ ivadomed -c config.json 

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/bin/ivadomed", line 5, in <module>
    from ivadomed.main import run_main
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/ivadomed/main.py", line 12, in <module>
    from ivadomed import testing as imed_testing
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/ivadomed/testing.py", line 12, in <module>
    from ivadomed import visualize as imed_visualize
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/ivadomed/visualize.py", line 8, in <module>
    from ivadomed import inference as imed_inference
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/ivadomed/inference.py", line 16, in <module>
    from ivadomed import training as imed_training
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/ivadomed/training.py", line 13, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/tensorboard/summary/v1.py", line 24, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/tensorboard/plugins/audio/summary.py", line 37, in <module>
    from tensorboard.plugins.audio import metadata
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/tensorboard/plugins/audio/metadata.py", line 21, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/GRAMES.POLYMTL.CA/u111358/.local/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 23, in <module>
    serialized_pb=_b('\n+tensorboard/compat/proto/tensor_shape.proto\x12\x0btensorboard\"{\n\x10TensorShapeProto\x12.\n\x03\x64im\x18\x02 \x03(\x0b\x32!.tensorboard.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB\x87\x01\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto\xf8\x01\x01\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

**Comment by andreanne-lemay** [comment]
Did you install ivadomed with `pip install` or with `git clone`? What `tensorboard` version are you using?

I looked up the error you had online and found this: https://github.com/tensorflow/models/issues/3995#issuecomment-400183986 
`pip install -U protobuf`

Currently I am not able to reproduce the error, maybe installing this library will solve the problem.

**Comment by mpompolas** [comment]
I missed that one.
pip install -U protobuf solved the issue.

Thanks for your help
