### ISSUE TITLE
Failure to convert BIDS to HDF5

### ISSUE THREAD

**Issue by leandervaneekelen** [ivadomed/ivadomed#540]
Whenever a HeMIS experiment is started, the adaptive loader of IvadoMed converts the given BIDS dataset to HDF5 if a `.hdf5` file doesn't exist already. My experiments are currently failing on this conversion, with the following error:

<details>
<summary>Traceback</summary>

~~~
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p114001/ivadomed/ivadomed/main.py", line 382, in <module>
    run_main()
  File "/home/GRAMES.POLYMTL.CA/p114001/ivadomed/ivadomed/main.py", line 375, in run_main
    run_command(context=context,
  File "/home/GRAMES.POLYMTL.CA/p114001/ivadomed/ivadomed/main.py", line 180, in run_command
    ds_valid = imed_loader.load_dataset(**{**loader_params,
  File "/home/GRAMES.POLYMTL.CA/p114001/ivadomed/ivadomed/loader/loader.py", line 73, in load_dataset
    dataset = imed_adaptative.HDF5Dataset(root_dir=bids_path,
  File "/home/GRAMES.POLYMTL.CA/p114001/ivadomed/ivadomed/loader/adaptative.py", line 508, in __init__
    hdf5_file = Bids_to_hdf5(root_dir,
  File "/home/GRAMES.POLYMTL.CA/p114001/ivadomed/ivadomed/loader/adaptative.py", line 306, in __init__
    self._load_filenames()
  File "/home/GRAMES.POLYMTL.CA/p114001/ivadomed/ivadomed/loader/adaptative.py", line 420, in _load_filenames
    grp[key].attrs['gt_filenames'] = input_metadata['gt_filenames']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/GRAMES.POLYMTL.CA/p114001/miniconda3/envs/leander_ivadomed/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 100, in __setitem__
    self.create(name, data=value)
  File "/home/GRAMES.POLYMTL.CA/p114001/miniconda3/envs/leander_ivadomed/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 184, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1632, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1654, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1709, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
~~~
</details>

I use the following call: `python3.8 ~/ivadomed/ivadomed/main.py --config ./hemis_exp.json` and[ this `.json` config file](https://pastebin.com/x6pKyGWA), on the latest main branch of IvadoMed.

Are there any glaring mistakes in the config file that I might've missed?

**Comment by andreanne-lemay** [comment]
Thank you for opening this issue!

I looked into it this morning and was able to reproduce this error (I used the [sample dataset ](https://github.com/ivadomed/data_example_spinegeneric) used for tutorials).

It is caused by the fact that NoneType cannot be encode in HDF5 (https://stackoverflow.com/questions/46906889/how-to-store-null-value-in-hdf5-table). 

While trying to reproduce this error, I encountered an other error, so I opened a branch to fix the HeMIS related bugs: https://github.com/ivadomed/ivadomed/pull/541. Feel free to contribute to this branch if you find new errors. I'll try to fix the code to work without the "None" for the missing gt.

Your config file seems good to me. In HeMISUnet:target_lst, you put a list of 2 modalities. If you do so, you might have a shape discrepancy during the training since the GT will use both datasets. If you have one class, but use 2 GTs you'll get these shapes: BATCHx1xHxW vs. BATCHx2xHxW which will trigger an error.

**Comment by leandervaneekelen** [comment]
> Your config file seems good to me. In HeMISUnet:target_lst, you put a list of 2 modalities. If you do so, you might have a shape discrepancy during the training since the GT will use both datasets. If you have one class, but use 2 GTs you'll get these shapes: BATCHx1xHxW vs. BATCHx2xHxW which will trigger an error.

So if I understood this correctly, `HeMISUnet:target_lst` specifies the modality from which it will read the ground truth? Assuming co-registered data (and GT), it would then be preferable to specify the modality everything was co-registered to, so not to get a potential shape mismatch?

**Comment by andreanne-lemay** [comment]
Yes exactly!
