### ISSUE TITLE
automate_training doesn't work with --fixed-split flag

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#702]
While working on the integration of the new loader, I found that the `automate_training.py` script doesn't work with the flag `--fixed-split`. It seems to work without the flag.

It may not have worked for a while because the first argument for `get_new_subject_split` [here](https://github.com/ivadomed/ivadomed/blob/86da257c5f1c7d5841e693fbeeb8077fc3f33ff0/ivadomed/scripts/automate_training.py#L155) is `path_folder` instead of `path_data`. There is no need to fix this argument now, as it is removed in the new loader integration in #699.

However, the following error message remains and should be fixed after the merge of #699.
```
Traceback (most recent call last):
  File "ivadomed/scripts/automate_training.py", line 798, in <module>
    main()
  File "ivadomed/scripts/automate_training.py", line 783, in main
    automate_training(file_config=args.config,
  File "ivadomed/scripts/automate_training.py", line 704, in automate_training
    val_df = pd.DataFrame(validation_scores, columns=[
UnboundLocalError: local variable 'validation_scores' referenced before assignment
```

Here is the command I used: `python ivadomed/scripts/automate_training.py -c ivadomed/config/config.json -ch ivadomed/scripts/hyperparameters_training.json -n 10 --all-combin --fixed-split`

**Comment by dyt811** [comment]
@mariehbourget, now that #699 is merged, could you try again? I just briefly tried it on PC and crashing...
![image](https://user-images.githubusercontent.com/6720068/111246735-2f22ab80-85dd-11eb-845a-d40c4554252e.png)
**but given PC platform is not fully tested and automate_training is known for fun behaviours**, could you test on whichever platform you have and let me know if you still see this? 

If you do, I will add this to the pile of testing/evaluation I need to do with automated_training as a potential scenario. Thanks.

**Comment by mariehbourget** [comment]
Yes, the error remains the same on my side (error in the first comment) in Ubuntu.
I think it's because the `validation scores` in line 702 is in the `if not fixed_split` condition, and should be outside the condition.

However, the error you have happens earlier in the code in `split_dataset` on line 668. On my side, the split_dataset works as expected. I have not seen that error before while working on the new loader, I'm not sure what is going on there. For reference, I'm using the `data_example_spinegeneric` dataset from tutorial [One-class segmentation with 2D U-Net](https://ivadomed.org/en/latest/tutorials/one_class_segmentation_2d_unet.html#one-class-segmentation-with-2d-u-net).
