### ISSUE TITLE
HeMIS training fails because of missing task attribute

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#703]
For the new loader integration, I tried training with HeMIS architecture, it fails because of a missing attribute `task` in `HDF5Dataset`. It happens on master branch as well.

Here is the error:
```
Traceback (most recent call last):
  File "/home/mhbourget/venv-ivadomed-38c/bin/ivadomed", line 11, in <module>
    load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
  File "/home/mhbourget/ivadomed/ivadomed/main.py", line 528, in run_main
    run_command(context=context,
  File "/home/mhbourget/ivadomed/ivadomed/main.py", line 361, in run_command
    metric_fns = imed_metrics.get_metric_fns(ds_train.task)
AttributeError: 'HDF5Dataset' object has no attribute 'task'
```

**Comment by gisellemartel** [comment]
Is this something that should be addressed prior or after the integration of the new pipeline?

**Comment by mariehbourget** [comment]
> Is this something that should be addressed prior or after the integration of the new pipeline?

The integration PR will most likely be ready for review today, so I would say after.
Also I just found a draft PR that is related to the same issue #541.
