### ISSUE TITLE
`Type 'tensor(bool)'` error when loading .ONNX representation of `seg_exvivo_gm-wm_t2`

### ISSUE THREAD

**Issue by joshuacwnewton** [ivadomed/ivadomed#749]
> **Note:** Creating this issue using @charleygros's comment on https://github.com/neuropoly/spinalcordtoolbox/pull/3321#issuecomment-810725960

The error occurs when loading the .ONNX model file using `onnxruntime.InferenceSession(model_path)`: 

```
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 245, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 207, in main
    nii_lst, target_lst = imed_inference.segment_volume(path_model, input_filenames, options=options)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 264, in segment_volume
    preds = model(img) if fname_model.endswith('.pt') else onnx_inference(fname_model, img)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 377, in onnx_inference
    ort_session = onnxruntime.InferenceSession(model_path)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (281) of operator (ScatterND) in node (ScatterND_160) is invalid.
```

This looks to be the same error message as https://github.com/microsoft/onnxruntime/issues/1807. That link suggests that the problem is due to indexing using a boolean tensor, which doesn't comply with the ONNX spec. If this is indeed the cause, then https://github.com/microsoft/onnxruntime/issues/1807#issuecomment-530508235 / https://github.com/onnx/onnx/issues/2302 suggests to use [`torch.where`](https://pytorch.org/docs/stable/generated/torch.where.html) to turn the boolean tensor into absolute indices. 

(I haven't looked at the model definition, though, so I can't confirm this yet.)

**Comment by joshuacwnewton** [comment]
Here's the relevant ONNX PR for `ScatterND`: https://github.com/onnx/onnx/pull/2220

> This will support the exporting of `torch.masked_scatter`, `torch.index_put`, `torch.copy_`, `tf.scatter_nd_update`, etc.

So, if the PT model definition has one of these operators, that might be where to look.

**Comment by joshuacwnewton** [comment]
FWIW, I also tried loading v1 of the model (from [r20210218](https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/releases/tag/r20210218)) and the issue was present there, too:

<details>
<summary> Commands and traceback </summary>

```python
>>> import onnxruntime
>>> old_model_path = "model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg-r20210218/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg.onnx"
>>> onnxruntime.InferenceSession(old_model_path)

---------------------------------------------------------------------------
InvalidGraph                              Traceback (most recent call last)
<ipython-input-4-1bd4a66724bb> in <module>
      5 
      6 old_model_path = "model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg-r20210218/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg.onnx"
----> 7 onnxruntime.InferenceSession(old_model_path)

~/repos/ivadomed/venv/lib/python3.8/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options, providers)
    156         self._path_or_bytes = path_or_bytes
    157         self._sess_options = sess_options
--> 158         self._load_model(providers or [])
    159         self._enable_fallback = True
    160         Session.__init__(self, self._sess)

~/repos/ivadomed/venv/lib/python3.8/site-packages/onnxruntime/capi/session.py in _load_model(self, providers)
    175             raise TypeError("Unable to load from type '{0}'".format(type(self._path_or_bytes)))
    176 
--> 177         self._sess.load_model(providers)
    178 
    179         self._sess_options = self._sess.session_options

InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (281) of operator (ScatterND) in node (ScatterND_160) is invalid.
</details>

**Comment by joshuacwnewton** [comment]
I tried re-exporting the `.pt` model as `.onnx` using ivadomed's `convert_to_onnx.py` script:

```console
> python3 ivadomed/scripts/convert_to_onnx.py -d 2 -n 1 -m model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.pt 
/home/joshua/repos/ivadomed/ivadomed/models.py:445: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  preds = nn.ReLU()(x) / nn.ReLU()(x).max() if bool(nn.ReLU()(x).max()) else nn.ReLU()(x)
/home/joshua/repos/ivadomed/ivadomed/models.py:447: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if preds.shape[1] > 1:
```

The warnings above seem valuable! Linking the relevant section of code (from the warnings) here:

https://github.com/ivadomed/ivadomed/blob/34551756dd6cc3cbec7800a691683096d6a7305b/ivadomed/models.py#L444-L451


<details>
<summary> Still able to reproduce the error, too... </summary>

```python
>>> import onnxruntime
>>> onnxruntime.InferenceSession( "model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.onnx")

---------------------------------------------------------------------------
InvalidGraph                              Traceback (most recent call last)
<ipython-input-1-1b99053d6fb8> in <module>
      2 
      3 model_path = "model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.onnx"
----> 4 onnxruntime.InferenceSession(model_path)

~/repos/ivadomed/venv/lib/python3.8/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options, providers)
    156         self._path_or_bytes = path_or_bytes
    157         self._sess_options = sess_options
--> 158         self._load_model(providers or [])
    159         self._enable_fallback = True
    160         Session.__init__(self, self._sess)

~/repos/ivadomed/venv/lib/python3.8/site-packages/onnxruntime/capi/session.py in _load_model(self, providers)
    175             raise TypeError("Unable to load from type '{0}'".format(type(self._path_or_bytes)))
    176 
--> 177         self._sess.load_model(providers)
    178 
    179         self._sess_options = self._sess.session_options

InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (281) of operator (ScatterND) in node (ScatterND_160) is invalid.
```
</details>

**Comment by joshuacwnewton** [comment]
This [StackOverflow thread](https://stackoverflow.com/a/66749078) has a possible answer for the PyTorch warning:

> This warning occurs, when one tries to `torch.jit.trace` models which have data dependent control flow.

So, if we remove the two branching paths, then I _think_ we can address the warnings, and therefore (hopefully) be able to export this to `.ONNX`. 

### First branching path

https://github.com/ivadomed/ivadomed/blob/34551756dd6cc3cbec7800a691683096d6a7305b/ivadomed/models.py#L445

The `if` is only here to prevent division by zero. (`bool(nn.ReLU()(x).max())` is `False` only when `nn.Relu(x).max() == 0`) 

In that case, `nn.Relu(x).max() == 0` means that `nn.Relu(x)` (the `else` case) would just be a zero tensor. I think there are a few non-branching ways of handling this, for example:

```python
# 0 / 0 for float tensors results in `nan`
>>> tensor_ReLU = torch.tensor([0., 0., 0.])
>>> tensor_ReLU_max = torch.tensor(0.)
>>> preds = tensor_ReLU.div(tensor_ReLU_max)
tensor([nan, nan, nan])
# Solution
>>> preds[torch.isnan(preds)] = 0. 
tensor([0., 0., 0.])
``` 

### Second branching path

https://github.com/ivadomed/ivadomed/blob/34551756dd6cc3cbec7800a691683096d6a7305b/ivadomed/models.py#L446-L447

This is more related to model configuration, isn't it? So, I'm wondering if the branching could be handled in `__init__()` rather than in the forward pass.

**Comment by charleygros** [comment]
... Wow... Just WOW! Thanks so much @joshuacwnewton for all these investigations!!

> So, if we remove the two branching paths mentioned in the warnings, then I _think_ we'll be able to export this to `.ONNX` without error.

Really?! Can we just try? :-)

> I think there are a few non-branching ways of handling this, for example:

Your suggestion sounds all relevant to me!

> This is more related to model configuration, isn't it? So, I'm wondering if the branching could be handled in `__init__()` rather than in the forward pass.

Yes, absolutely correct! We have this information from [out_channels](https://github.com/ivadomed/ivadomed/blob/34551756dd6cc3cbec7800a691683096d6a7305b/ivadomed/models.py#L472).

**Comment by joshuacwnewton** [comment]
> Yes, absolutely correct! We have this information from [out_channels](https://github.com/ivadomed/ivadomed/blob/34551756dd6cc3cbec7800a691683096d6a7305b/ivadomed/models.py#L472).

Ah, thanks for pointing this out! We even already use this for a separate check:

https://github.com/ivadomed/ivadomed/blob/34551756dd6cc3cbec7800a691683096d6a7305b/ivadomed/models.py#L455-L457

> > So, if we remove the two branching paths mentioned in the warnings, then I _think_ we'll be able to export this to `.ONNX` without error.
> 
> Really?! Can we just try? :-)

I'll open up a PR. :slightly_smiling_face:  

I believe the model may need to be retrained, though, as I'm getting this warning when I try to convert the `.pt` file with the changes made:

```
/home/joshua/repos/ivadomed/venv/lib/python3.8/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'ivadomed.models.Decoder' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
```

**Comment by joshuacwnewton** [comment]
I've hidden the comments above because #752 turned out to not address this issue, so further investigation is needed.

**Comment by joshuacwnewton** [comment]
There is also new motivation for fixing this issue: If we can get all of SCT's models in ONNX form, we might be able to shave off a costly `torch` dependency (which takes up between 600MB and 1.3GB depending on whether the CPU/GPU version is installed). By removing torch, a `pip` install of SCT would be much more viable.

More information in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1526#issuecomment-844079364.

**Comment by joshuacwnewton** [comment]
> There is also new motivation for fixing this issue: If we can get all of the models that SCT uses in ONNX form, then SCT might be able to shave off a costly `torch` dependency (which takes up between 600MB and 1.3GB depending on whether the CPU/GPU version is installed). By removing torch, a `pip` install of SCT would be much more viable.

After investigation in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3396, I learned that even if ivadomed successfully converts all of SCT's models to ONNX, SCT won't be able to avoid torch/torchvision as dependencies, because those libraries are also needed for pre/postprocessing operations when performing inference.

Because of that, there is less benefit to addressing this issue, and therefore I'm going to un-assign myself from this issue and leave it for now.
