### ISSUE TITLE
Participants.tsv creates an error when entries are dashes

### ISSUE THREAD

**Issue by mpompolas** [ivadomed/ivadomed#796]
## Issue description
Training fails on `sct-testing-large`.
The issue appears to be triggered by the presence of dashes `-` in the `participants.tsv` file due to the new loader based on `pybids`.

![image](https://user-images.githubusercontent.com/23224563/118849677-f7b2d280-b89d-11eb-956a-72763407366f.png)

### Current behavior

```
/home/nas/anaconda3/envs/GuillaumeConverter/bin/python /home/nas/PycharmProjects/ivadomed/ivadomed/main.py -c /home/nas/PycharmProjects/ivadomed-personal-scripts/config.json
Adding the following keys to the configuration file
    loader_parameters: extensions: []
    loader_parameters: is_input_dropout: False
    split_dataset: split_method: participant_id
    split_dataset: data_testing: {'data_type': None, 'data_value': []}
    default_model: is_2d: True


Output path already exists: /home/nas/PycharmProjects/ivadomed-personal-scripts/log_to_delete
Using GPU ID 0

Selected architecture: Unet, with the following parameters:
	dropout_rate: 0.3
	bn_momentum: 0.9
	depth: 3
	is_2d: True
	folder_name: my_model
	in_channel: 1
	out_channel: 1
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1119, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1244, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1259, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1450, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 558, in <module>
    run_main()
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 551, in run_main
    run_command(context=context,
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 336, in run_command
    bids_df = imed_loader_utils.BidsDataframe(loader_params, path_output, derivatives=True)
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/utils.py", line 624, in __init__
    self.create_bids_dataframe()
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/utils.py", line 695, in create_bids_dataframe
    df_next = self.add_tsv_metadata(df_next, path_data, layout)
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/utils.py", line 743, in add_tsv_metadata
    if layout.get_collections(level='dataset'):
  File "/home/nas/anaconda3/envs/GuillaumeConverter/lib/python3.8/site-packages/bids/layout/layout.py", line 823, in get_collections
    index = load_variables(self, types=types, levels=level,
  File "/home/nas/anaconda3/envs/GuillaumeConverter/lib/python3.8/site-packages/bids/variables/io.py", line 97, in load_variables
    dataset = _load_tsv_variables(layout, t, dataset, scope=scope,
  File "/home/nas/anaconda3/envs/GuillaumeConverter/lib/python3.8/site-packages/bids/variables/io.py", line 423, in _load_tsv_variables
    _data = f.get_df(include_timing=False)
  File "/home/nas/anaconda3/envs/GuillaumeConverter/lib/python3.8/site-packages/bids/layout/models.py", line 426, in get_df
    self.data = pd.read_csv(self.path, sep='\t', na_values='n/a',
  File "/home/nas/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/nas/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 458, in _read
    data = parser.read(nrows)
  File "/home/nas/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1196, in read
    ret = self._engine.read(nrows)
  File "/home/nas/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 2155, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1073, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1126, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1244, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1259, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1450, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

Process finished with exit code 1

```

### System description

Ubuntu 20.04
pybids 0.12.4
pandas 1.1.3

### Easy potential solution - Changing the participants.tsv `-` entries on the git annex
First copy `participants.tsv` to a different folder.
Then substitute the dash `-` entries with `nan` within `participants.tsv`.

import pandas as pd
df = pd.read_table("/home/nas/Desktop/sct_testing_large_participants_old.tsv", encoding="ISO-8859-1")

df_new = df.replace("-", "nan")
df_new.to_csv("/home/nas/ivado_project/Datasets/sct-testing-large/participants.tsv", sep='\t', index=False)

**Comment by jcohenadad** [comment]
> Then substitute the dash - entries with nan within participants.tsv.

hum... i'm not a big fan of having fields with the string value "nan". What if, e.g. a new scanner model is also called "nan". Can we find another solution?  I guess leaving the fields empty will also break?

**Comment by mariehbourget** [comment]
> hum... i'm not a big fan of having fields with the string value "nan". What if, e.g. a new scanner model is also called "nan". Can we find another solution? I guess leaving the fields empty will also break?

BIDS recommend using `n/a` for missing values: https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file
So I suppose `pybids` would work with `n/a`.

**Comment by jcohenadad** [comment]
@mariehbourget thank you for the tips!
@mpompolas will test if it works
if it works, @alexfoias can you please update the TSV file?
thanks!

**Comment by mpompolas** [comment]
confirmed. 
`n/a` works

**Comment by alexfoias** [comment]
okay I will take care of it.

**Comment by alexfoias** [comment]
@mpompolas updated in `sct-testing-large/af/update_participants` Do you think you can test it out? thanks

**Comment by mpompolas** [comment]
hi @alexfoias .

Just checked your branch and the training works.
You can merge the changes

**Comment by alexfoias** [comment]
@kousu is the procedure listed [here](https://github.com/neuropoly/data-management/blob/master/internal-server.md#committing) up to date for merging a branch ?

**Comment by kousu** [comment]
@alexfoias Yes, it is. But even if it isn't, can you try it and report any problems you have with it? If it doesn't seem to work for you, please open a bug on that repo about it. Up until the `git push` part there's no harm done, you can always undo by just recloning the repo.

**Comment by alexfoias** [comment]
@kousu is the branch merged ?
