### ISSUE TITLE
Training on spinegeneric dataset gives size mismatches between image and ground truth

### ISSUE THREAD

**Issue by mpompolas** [ivadomed/ivadomed#797]
## Issue description
Training on the `spinegeneric/data-multi-subject` dataset:
https://github.com/spine-generic/data-multi-subject

### Current behavior

Error reports input and gt have different dimensions

```
Dataframe has been saved in /home/nas/PycharmProjects/ivadomed-personal-scripts/log_to_delete/bids_dataframe.csv.

Selected transformations for the ['training'] dataset:
	Resample: {'wspace': 0.75, 'hspace': 0.75, 'dspace': 1}
	CenterCrop: {'size': [128, 128]}
	RandomAffine: {'degrees': 5, 'scale': [0.1, 0.1], 'translate': [0.03, 0.03], 'applied_to': ['im', 'gt']}
	ElasticTransform: {'alpha_range': [28.0, 30.0], 'sigma_range': [3.5, 4.5], 'p': 0.1, 'applied_to': ['im', 'gt']}
	NumpyToTensor: {}
	NormalizeInstance: {'applied_to': ['im']}

Selected transformations for the ['validation'] dataset:
	Resample: {'wspace': 0.75, 'hspace': 0.75, 'dspace': 1}
	CenterCrop: {'size': [128, 128]}
	NumpyToTensor: {}
	NormalizeInstance: {'applied_to': ['im']}
Loading dataset: 100%|██████████| 9/9 [00:00<00:00, 230.00it/s]
Traceback (most recent call last):
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 558, in <module>
    run_main()
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 551, in run_main
    run_command(context=context,
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 371, in run_command
    ds_valid = get_dataset(bids_df, loader_params, valid_lst, transform_valid_params, cuda_available, device,
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 117, in get_dataset
    ds = imed_loader.load_dataset(bids_df, **{**loader_params, **{'data_list': data_lst,
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/loader.py", line 115, in load_dataset
    dataset.load_filenames()
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/loader.py", line 640, in load_filenames
    seg_pair = SegmentationPair(input_filenames, gt_filenames, metadata=metadata, slice_axis=self.slice_axis,
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/loader.py", line 250, in __init__
    raise RuntimeError('Input and ground truth with different dimensions.')
RuntimeError: Input and ground truth with different dimensions.

Process finished with exit code 1
```

### Steps to reproduce
`Config file:`

```
{
    "command": "train",
    "gpu_ids": [0],
    "path_output": "/home/nas/PycharmProjects/ivadomed-personal-scripts/log_to_delete",
    "model_name": "my_model",
    "debugging": true,
    "object_detection_params": {
        "object_detection_path": null,
        "safety_factor": [1.0, 1.0, 1.0]
    },
    "loader_parameters": {
        "path_data": ["/home/nas/ivado_project/Datasets/data-multi-subject"],
        "subject_selection": {"n": [], "metadata": [], "value": []},
        "target_suffix": ["_seg-manual"],
        "contrast_params": {
            "training_validation": ["T1w", "T2w"],
            "testing": ["T1w", "T2w"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": true
        },
        "slice_axis": "axial",
        "multichannel": false,
        "soft_gt": false
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6,
        "center_test": [],
        "method": "per_patient",
        "balance": null,
        "train_fraction": 0.1,
        "test_fraction": 0.7
    },
    "training_parameters": {
        "batch_size": 16,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 2,
            "early_stopping_patience": 50,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 0.001,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-2
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.9,
        "depth": 3
    },
    "FiLMedUnet": {
        "applied": false,
        "metadata": "institution_id",
        "film_layers": [0, 1, 0, 0, 0, 0, 0, 0]
    },
    "Modified3DUNet": {
        "applied": false,
        "length_3D": [128, 128, 16],
        "stride_3D": [128, 128, 16],
        "attention": false,
        "n_filters": 8
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {
        "remove_noise": {"thr": -1},
        "keep_largest": {},
        "binarize_prediction": {"thr": 0.5},
        "uncertainty": {"thr": -1, "suffix": "_unc-vox.nii.gz"},
        "fill_holes": {},
        "remove_small": {"unit": "vox", "thr": 3}
    },
    "evaluation_parameters": {
        "target_size": {"unit": "vox", "thr": [20, 100]},
        "overlap": {"unit": "vox", "thr": 3}
    },
    "transformation": {
        "Resample":
        {
            "wspace": 0.75,
            "hspace": 0.75,
            "dspace": 1
        },
        "CenterCrop": {
            "size": [128, 128]},
        "RandomAffine": {
            "degrees": 5,
            "scale": [0.1, 0.1],
            "translate": [0.03, 0.03],
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "ElasticTransform": {
			"alpha_range": [28.0, 30.0],
			"sigma_range":  [3.5, 4.5],
			"p": 0.1,
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
      "NumpyToTensor": {},
      "NormalizeInstance": {"applied_to": ["im"]}
    }
}
```

### Source of the problems
Was there a cropping step that was missed during preparation of the datasets?

Some of the problematic pairs (image/gt):
```
['/derivatives/labels/sub-beijingGE03/anat/sub-beijingGE03_T1w_RPI_r_seg-manual.nii.gz']
['/data-multi-subject/derivatives/labels/sub-brnoUhb08/anat/sub-brnoUhb08_T1w_RPI_r_seg-manual.nii.gz']
```

Image: sub-beijingGE03_T1w.nii.gz - `320x320x188`        
GT: sub-beijingGE03_T1w_RPI_r_seg-manual.nii.gz - `188x320x320`

Image: sub-brnoUhb08_T1w.nii.gz - `188, 512, 512`
GT: sub-brnoUhb08_T1w_RPI_r_seg-manual.nii.gz - `188x320x320`

**Comment by jcohenadad** [comment]
yes, the "r" in the file name means "resampled". The full processing script is [here](https://github.com/spine-generic/spine-generic/blob/master/process_data.sh).

i suggest to move this issue thread in this repos: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord
or it could also be moved here: https://github.com/spine-generic/spine-generic/issues

we need to find a good strategy for handling these derivatives. Maybe what we've done for the uk-biobank project is the way to go (ie: create a BIDS processed dataset). @sandrinebedard can also comment

**Comment by sandrinebedard** [comment]
Yes, here the image linked with the ground truth is sub-beijingGE03_T1w_RPI_r.nii.gz and not sub-beijingGE03_T1w.nii.gz for example, but the image in question should only be in the processed data of spine_generic and not in the spine-generic dataset, @jcohenadad do you still have those results? 

We could definitly follow what we talked about in this [issue](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/issues/29)

Also having a spine-generic-processed dataset and only having the derivatives in that dataset (as we did for UK-Biobank) would be more accurate since the segmentations are generated from the processed data and not the original.

**Comment by jcohenadad** [comment]
> @jcohenadad do you still have those results?

yes! `duke:projects/spine_generic/results_multi_20200907` 😊
