### ISSUE TITLE
Error when training with multichannel selection

### ISSUE THREAD

**Issue by mpompolas** [ivadomed/ivadomed#808]
I try to train a multichannel model ("loader_parameters": {"multichannel": true}).

The same config.json file with multchannel:False runs smoothly.

### Current behavior

```
Adding the following keys to the configuration file
    loader_parameters: extensions: []
    loader_parameters: roi_params: {'suffix': None, 'slice_filter_roi': None}
    loader_parameters: is_input_dropout: False
    split_dataset: split_method: participant_id
    split_dataset: data_testing: {'data_type': None, 'data_value': []}
    default_model: is_2d: True


Creating output path: /home/nas/PycharmProjects/ivadomed-personal-scripts/log_to_delete
Using GPU ID 0

Selected architecture: Unet, with the following parameters:
	dropout_rate: 0.3
	bn_momentum: 0.9
	depth: 3
	is_2d: True
	folder_name: my_model
	in_channel: 3
	out_channel: 1
Dataframe has been saved in /home/nas/PycharmProjects/ivadomed-personal-scripts/log_to_delete/bids_dataframe.csv.
After splitting: train, validation and test fractions are respectively 0.5, 0.3 and 0.2 of participant_id.

Selected transformations for the ['training'] dataset:
	Resample: {'wspace': 0.75, 'hspace': 0.75, 'dspace': 1}
	CenterCrop: {'size': [128, 128]}
	RandomAffine: {'degrees': 5, 'scale': [0.1, 0.1], 'translate': [0.03, 0.03], 'applied_to': ['im', 'gt']}
	ElasticTransform: {'alpha_range': [28.0, 30.0], 'sigma_range': [3.5, 4.5], 'p': 0.1, 'applied_to': ['im', 'gt']}
	NumpyToTensor: {}
	NormalizeInstance: {'applied_to': ['im']}

Selected transformations for the ['validation'] dataset:
	Resample: {'wspace': 0.75, 'hspace': 0.75, 'dspace': 1}
	CenterCrop: {'size': [128, 128]}
	NumpyToTensor: {}
	NormalizeInstance: {'applied_to': ['im']}
Loading dataset: 100%|██████████| 9/9 [00:00<00:00, 241.17it/s]
Traceback (most recent call last):
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 558, in <module>
    run_main()
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 551, in run_main
    run_command(context=context,
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 371, in run_command
    ds_valid = get_dataset(bids_df, loader_params, valid_lst, transform_valid_params, cuda_available, device,
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/main.py", line 117, in get_dataset
    ds = imed_loader.load_dataset(bids_df, **{**loader_params, **{'data_list': data_lst,
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/loader.py", line 115, in load_dataset
    dataset.load_filenames()
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/loader.py", line 647, in load_filenames
    slice_seg_pair = seg_pair.get_pair_slice(idx_pair_slice, gt_type=self.task)
  File "/home/nas/PycharmProjects/ivadomed/ivadomed/loader/loader.py", line 412, in get_pair_slice
    input_slices.append(np.asarray(data_object[..., slice_index],
IndexError: index 14 is out of bounds for axis 2 with size 14

Process finished with exit code 1
```

### Steps to reproduce
Config file used:
```

{
    "command": "train",
    "gpu_ids": [0],
    "path_output": "/home/nas/PycharmProjects/ivadomed-personal-scripts/log_to_delete",
    "model_name": "my_model",
    "debugging": true,
    "object_detection_params": {
        "object_detection_path": null,
        "safety_factor": [1.0, 1.0, 1.0]
    },
    "loader_parameters": {
        "path_data": ["/home/nas/Consulting/ivado_project/Datasets/data_example_spinegeneric"],
        "subject_selection": {"n": [], "metadata": [], "value": []},
        "target_suffix": ["_seg-manual"],
        "contrast_params": {
            "training_validation": ["T1w", "T2w", "T2star"],
            "testing": ["T1w", "T2w", "T2star"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": true
        },
        "slice_axis": "axial",
        "multichannel": true,
        "soft_gt": false
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6,
        "center_test": [],
        "method": "per_patient",
        "balance": null,
        "train_fraction": 0.5,
        "test_fraction": 0.2
    },
    "training_parameters": {
        "batch_size": 16,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 2,
            "early_stopping_patience": 50,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 0.001,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-2
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.9,
        "depth": 3
    },
    "FiLMedUnet": {
        "applied": false,
        "metadata": "institution_id",
        "film_layers": [0, 1, 0, 0, 0, 0, 0, 0]
    },
    "Modified3DUNet": {
        "applied": false,
        "length_3D": [128, 128, 16],
        "stride_3D": [128, 128, 16],
        "attention": false,
        "n_filters": 8
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {
        "remove_noise": {"thr": -1},
        "keep_largest": {},
        "binarize_prediction": {"thr": 0.5},
        "uncertainty": {"thr": -1, "suffix": "_unc-vox.nii.gz"},
        "fill_holes": {},
        "remove_small": {"unit": "vox", "thr": 3}
    },
    "evaluation_parameters": {
        "target_size": {"unit": "vox", "thr": [20, 100]},
        "overlap": {"unit": "vox", "thr": 3}
    },
    "transformation": {
        "Resample":
        {
            "wspace": 0.75,
            "hspace": 0.75,
            "dspace": 1
        },
        "CenterCrop": {
            "size": [128, 128]},
        "RandomAffine": {
            "degrees": 5,
            "scale": [0.1, 0.1],
            "translate": [0.03, 0.03],
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "ElasticTransform": {
			"alpha_range": [28.0, 30.0],
			"sigma_range":  [3.5, 4.5],
			"p": 0.1,
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
      "NumpyToTensor": {},
      "NormalizeInstance": {"applied_to": ["im"]}
    }
}

```

## Environment

Ubuntu 20.04

**Comment by mariehbourget** [comment]
I was able to reproduce the same behavior with your config file i.e. fails in multichannel but works in single channel.

I may be wrong but I think that multichannel only works when all the contrasts are present for all the subjects. In `data_example_spinegeneric`, the subject `sub-hamburg01` does not have a `T2star`. I tried removing the `T2star` from the `contrast_params` in the config file, and multichannel is running as expected.

**Comment by rezazad68** [comment]
I also produced the same error and as @mariehbourget mentioned it is because of the missing contrast. The loader should raise an error for the missing contrast in this case. It is also interesting to know does ivadomed has a solution for subjects with missing contrasts? I mean if the majority of subjects have such contrast then why not using it?

**Comment by charleygros** [comment]
> does ivadomed has a solution for subjects with missing contrasts?

What do you think of [input-level dropout solution](https://github.com/ivadomed/ivadomed/pull/705) @rezazad68 ? If you try it, please let us know how it goes!! really keen to know

**Comment by rezazad68** [comment]
@charleygros thanks for the suggestion. I have added the `"is_input_dropout": true` to the `loader_parameters` but still same error if we have missing modalities.

**Comment by charleygros** [comment]
Mmmm I think you are right @rezazad68: this feature simulates missing modalities, BUT it does not cover the case where modalities are already missing! Which we should implement at some point since list of applications is growing!! Opening an issue.. (You are very welcome to work on this @rezazad68 if it pleases you :-) )
