### ISSUE TITLE
file missing in data_example_spinegeneric for estimate uncertainty tutorial

### ISSUE THREAD

**Issue by cakester** [ivadomed/ivadomed#863]
## Issue description
I am currently following the estimate uncertainty tutorial in https://ivadomed.org/en/latest/tutorials/uncertainty.html, and I got  FileNotFoundError: [Errno 2] No such file or directory: 'data_example_spinegeneric/trained_model\\/derivatives/dataset_description.json', derivatives/dataset_description.json file really does not exist inside the data_example_spinegeneric folder

### Expected behavior
 
add derivatives/dataset_description.json file inside data_example_spinegeneric folder

### Steps to reproduce
follow https://ivadomed.org/en/latest/tutorials/uncertainty.html

### Installed packages

<details open>
<summary> Output of <code>pip freeze</code> </summary>

```

```

</details>

**Comment by jcohenadad** [comment]
hum, the "\" in this path is suspicious: `data_example_spinegeneric/trained_model\/derivatives/dataset_description.json`

are you working on windows? could that explain the issue?

**Comment by cakester** [comment]
> hum, the `"\"` in this path is suspicious: `data_example_spinegeneric/trained_model\/derivatives/dataset_description.json`
> 
> are you working on windows? could that explain the issue?

derivatives/dataset_description.json does not exist in data_example_spinegeneric/trained_model to begin with, and it is expected to be there

**Comment by jcohenadad** [comment]
> derivatives/dataset_description.json does not exist in data_example_spinegeneric/trained_model to begin with, and it is expected to be there

ah! that's indeed a problem then. Maybe @charleygros or @andreanne-lemay you could look into this?

**Comment by cakester** [comment]
so after i copied dataset_description.json from data_example_spinegeneric/ to data_example_spinegeneric/trained_model/derivatives, i get
```
Traceback (most recent call last):
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hanna.ma\AppData\Local\Programs\Python\Python38\Scripts\ivadomed.exe\__main__.py", line 7, in <module>
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\main.py", line 566, in run_mai
n
    run_command(context=context,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\main.py", line 351, in run_com
mand
    bids_df = imed_loader_utils.BidsDataframe(loader_params, path_output, derivatives=True)
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\loader\utils.py", line 623, in
 __init__
    self.create_bids_dataframe()
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\loader\utils.py", line 668, in
 create_bids_dataframe
    layout = pybids.BIDSLayout(path_data, config=self.bids_config, indexer=indexer,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\bids\layout\layout.py", line 136, in __
init__
    root, description = validate_root(root, validate)
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\bids\layout\validation.py", line 73, in
 validate_root
    raise BIDSValidationError(
bids.exceptions.BIDSValidationError: 'dataset_description.json' is missing from project root. Every valid BIDS dataset mus
t have this file.
Example contents of 'dataset_description.json':
{"Name": "Example dataset", "BIDSVersion": "1.0.2"}
```

after the above error, i copied dataset_description in data_example_spinegeneric/trained_model as well, then i get

```
Traceback (most recent call last):
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hanna.ma\AppData\Local\Programs\Python\Python38\Scripts\ivadomed.exe\__main__.py", line 7, in <module>
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\main.py", line 566, in run_mai
n
    run_command(context=context,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\main.py", line 351, in run_com
mand
    bids_df = imed_loader_utils.BidsDataframe(loader_params, path_output, derivatives=True)
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\loader\utils.py", line 623, in
 __init__
    self.create_bids_dataframe()
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\loader\utils.py", line 668, in
 create_bids_dataframe
    layout = pybids.BIDSLayout(path_data, config=self.bids_config, indexer=indexer,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\bids\layout\layout.py", line 161, in __
init__
    self.add_derivatives(
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\bids\layout\layout.py", line 469, in ad
d_derivatives
    deriv_paths = validate_derivative_paths(paths, self, **kwargs)
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\bids\layout\validation.py", line 150, i
n validate_derivative_paths
    raise BIDSDerivativesValidationError(
bids.exceptions.BIDSDerivativesValidationError: Every valid BIDS-derivatives dataset must have a PipelineDescription.Name
field set inside 'dataset_description.json'.
Example: {'PipelineDescription': {'Name': 'Example pipeline'}}
```

after manually adding the key, i get

```
Traceback (most recent call last):
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hanna.ma\AppData\Local\Programs\Python\Python38\Scripts\ivadomed.exe\__main__.py", line 7, in <module>
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\main.py", line 566, in run_mai
n
    run_command(context=context,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\main.py", line 351, in run_com
mand
    bids_df = imed_loader_utils.BidsDataframe(loader_params, path_output, derivatives=True)
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\loader\utils.py", line 623, in
 __init__
    self.create_bids_dataframe()
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\loader\utils.py", line 705, in
 create_bids_dataframe
    raise RuntimeError("No subject files found. Check selection of parameters in config.json"
RuntimeError: No subject files found. Check selection of parameters in config.json and datasets compliance with BIDS speci
fication.
```

i copied config.json like the tutorial suggests

**Comment by mariehbourget** [comment]
Hi @cakester, the error you have means that ivadomed is looking for source images in the folder `trained_model` which it's not supposed to.
In your config file, make sure that:
- `path_data` points to the location of the dataset: `<PATH_TO_DATASET>/data_example_spinegeneric`
- `path_output` points to the trained model `<PATH_TO_DATASET>/data_example_spinegeneric/trained_model`

**Comment by cakester** [comment]
> Hi @cakester, the error you have means that ivadomed is looking for source images in the folder `trained_model` which it's not supposed to.
> In your config file, make sure that:
> 
> * `path_data` points to the location of the dataset: `<PATH_TO_DATASET>/data_example_spinegeneric`
> * `path_output` points to the trained model `<PATH_TO_DATASET>/data_example_spinegeneric/trained_model`

i am following the tutorials, and the command inside tutorials is test, am I suppose to run training before running test?

**Comment by mariehbourget** [comment]
The command `test` is right, the model is already trained in `trained_model`.
My guess is that you have `<PATH_TO_DATASET>/data_example_spinegeneric/trained_model` in `path_data` instead of `path_output`.

**Comment by cakester** [comment]
> The command `test` is right, the model is already trained in `trained_model`.
> My guess is that you have `<PATH_TO_DATASET>/data_example_spinegeneric/trained_model` in `path_data` instead of `path_output`.

you are right, now i corrected it and then it tells me im missing a key in dataset_description.json even though I manually added it
` ivadomed --test -c config.json --path-data data_example_spinegeneric --path-output data_example_spinegeneric/trained_model
2021-08-04 20:03:58.486 | INFO     | ivadomed.utils:init_ivadomed:408 -
ivadomed (2.7.4)

2021-08-04 20:03:58.490 | INFO     | ivadomed.main:set_output_path:197 - Output path already exists: data_example_spinegen
eric/trained_model
2021-08-04 20:03:58.551 | INFO     | ivadomed.utils:define_device:128 - Cuda is not available.
2021-08-04 20:03:58.553 | INFO     | ivadomed.utils:define_device:129 - Working on cpu.
2021-08-04 20:03:58.555 | INFO     | ivadomed.utils:display_selected_model_spec:144 - Selected architecture: Unet, with th
e following parameters:
2021-08-04 20:03:58.557 | INFO     | ivadomed.utils:display_selected_model_spec:147 -   dropout_rate: 0.3
2021-08-04 20:03:58.558 | INFO     | ivadomed.utils:display_selected_model_spec:147 -   bn_momentum: 0.1
2021-08-04 20:03:58.559 | INFO     | ivadomed.utils:display_selected_model_spec:147 -   depth: 3
2021-08-04 20:03:58.560 | INFO     | ivadomed.utils:display_selected_model_spec:147 -   is_2d: True
2021-08-04 20:03:58.562 | INFO     | ivadomed.utils:display_selected_model_spec:147 -   final_activation: sigmoid
2021-08-04 20:03:58.563 | INFO     | ivadomed.utils:display_selected_model_spec:147 -   folder_name: my_model
2021-08-04 20:03:58.564 | INFO     | ivadomed.utils:display_selected_model_spec:147 -   in_channel: 1
2021-08-04 20:03:58.565 | INFO     | ivadomed.utils:display_selected_model_spec:147 -   out_channel: 1
2021-08-04 20:03:58.571 | INFO     | ivadomed.loader.utils:create_bids_dataframe:667 - data_example_spinegeneric\
Traceback (most recent call last):
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hanna.ma\AppData\Local\Programs\Python\Python38\Scripts\ivadomed.exe\__main__.py", line 7, in <module>
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\main.py", line 566, in run_mai
n
    run_command(context=context,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\main.py", line 351, in run_com
mand
    bids_df = imed_loader_utils.BidsDataframe(loader_params, path_output, derivatives=True)
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\loader\utils.py", line 623, in
 __init__
    self.create_bids_dataframe()
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\ivadomed\loader\utils.py", line 668, in
 create_bids_dataframe
    layout = pybids.BIDSLayout(path_data, config=self.bids_config, indexer=indexer,
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\bids\layout\layout.py", line 161, in __
init__
    self.add_derivatives(
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\bids\layout\layout.py", line 469, in ad
d_derivatives
    deriv_paths = validate_derivative_paths(paths, self, **kwargs)
  File "c:\users\hanna.ma\appdata\local\programs\python\python38\lib\site-packages\bids\layout\validation.py", line 150, i
n validate_derivative_paths
    raise BIDSDerivativesValidationError(
bids.exceptions.BIDSDerivativesValidationError: Every valid BIDS-derivatives dataset must have a PipelineDescription.Name
field set inside 'dataset_description.json'.
Example: {'PipelineDescription': {'Name': 'Example pipeline'}}
`

**Comment by mariehbourget** [comment]
> you are right, now i corrected it and then it tells me im missing a key in dataset_description.json even though I manually added it

This is because the content of the `dataset_description.json` file you added manually is not right for the derivatives folder.
You don't have to add any file manually. I suggest you try again with the original dataset without adding anything.
When you run the command, the missing file will be added automatically with the right content.

**Comment by cakester** [comment]
> > you are right, now i corrected it and then it tells me im missing a key in dataset_description.json even though I manually added it
> 
> This is because the content of the `dataset_description.json` file you added manually is not right for the derivatives folder.
> You don't have to add any file manually. I suggest you try again with the original dataset without adding anything.
> When you run the command, the missing file will be added automatically with the right content.

thanks, now works

**Comment by cakester** [comment]
updated on hm/long_tests
