### ISSUE TITLE
Fix issues in cascaded architecture tutorial

### ISSUE THREAD

**Issue by copperwiring** [ivadomed/ivadomed#921]
There are some minor issues in the documentation of [Cascaded Tutorial](https://ivadomed.org/en/latest/tutorials/cascaded_architecture.html), description of them is mentioned below:

### Issue 1:
In the section of [Configuration File](https://ivadomed.org/en/latest/tutorials/cascaded_architecture.html#configuration-file), it is written,

`"object_detection_path": "<PATH_TO_DATASET>/data_example_spinegeneric/trained_model/seg_sc_t1-t2-t2s-mt"
`

It should be:

`"object_detection_path": "<PATH_TO_DATASET>/trained_model/seg_sc_t1-t2-t2s-mt"
`

### Issue 2:

Training it using the config file gives error `tupple index out of range`

```
Traceback (most recent call last):
  File "/home/srishtiy/dev/neuropoly/ivadomed/venv-ivadomed/bin/ivadomed", line 11, in <module>
    load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
  File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/main.py", line 566, in run_main
    run_command(context=context,
  File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/main.py", line 386, in run_command
    ds_valid = get_dataset(bids_df, loader_params, valid_lst, transform_valid_params, cuda_available, device,
  File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/main.py", line 117, in get_dataset
    ds = imed_loader.load_dataset(bids_df, **{**loader_params, **{'data_list': data_lst,
  File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/loader/loader.py", line 88, in load_dataset
    dataset = BidsDataset(bids_df=bids_df,
  File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/loader/bids_dataset.py", line 91, in __init__
    bounding_box_dict = imed_obj_detect.load_bounding_boxes(object_detection_params,
  File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/object_detection/utils.py", line 248, in load_bounding_boxes
    bounding_box_dict = generate_bounding_box_file(subject_path_list,
  File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/object_detection/utils.py", line 122, in generate_bounding_box_file
    ras_orientation = nib.as_closest_canonical(object_mask)
  File "/home/srishtiy/dev/neuropoly/ivadomed/venv-ivadomed/lib/python3.8/site-packages/nibabel/funcs.py", line 205, in as_closest_canonical
    img = img.as_reoriented(io_orientation(img.affine))
  File "/home/srishtiy/dev/neuropoly/ivadomed/venv-ivadomed/lib/python3.8/site-packages/nibabel/orientations.py", line 55, in io_orientation
    q, p = affine.shape[0] - 1, affine.shape[1] - 1
IndexError: tuple index out of range
```

**Comment by copperwiring** [comment]
The other issue which I am unsure of is this. The same tutorial [mentions](https://ivadomed.org/en/latest/tutorials/cascaded_architecture.html#configuration-file):

```
loader_parameters:target_suffix: Suffix of the ground truth segmentation. The ground truth are located under the DATASET/derivatives/labels folder. The suffix for CSF labels in this dataset is _csfseg-manual:

"target_suffix": ["_csfseg-manual"]

```

however, there is no such file with suffix `_csfeg-manual`

![image](https://user-images.githubusercontent.com/23316280/130715677-82930c6e-1115-48c2-9b3b-100474f799cc.png)

``````

**Comment by copperwiring** [comment]
I found the issue but since it involves `nibabel` lib, I have not found a fix so far. Here is the issue.

Issue comes from `ivadomed/ivadomed/object_detection/utils.py`, line 123

`  ras_orientation = nib.as_closest_canonical(object_mask)
`
the function `as_closest_canonical` takes an argument `object_mask` which is a ` 'nibabel.nifti1.Nifti1Image'` data type. This function

```
def as_closest_canonical(img, enforce_diag=False):
    """ Return `img` with data reordered to be closest to canonical

    Canonical order is the ordering of the output axes.

    Parameters
    ----------
    img : ``spatialimage``
    enforce_diag : {False, True}, optional
       If True, before transforming image, check if the resulting image
       affine will be close to diagonal, and if not, raise an error

    Returns
    -------
    canonical_img : ``spatialimage``
       Version of `img` where the underlying array may have been
       reordered and / or flipped so that axes 0,1,2 are those axes in
       the input data that are, respectively, closest to the output axis
       orientation.  We modify the affine accordingly.  If `img` is
       already has the correct data ordering, we just return `img`
       unmodified.
    """
    # Get the image class to transform the data for us
    img = img.as_reoriented(io_orientation(img.affine))
    .
    .
    .
```
is a function from `nibabel` library. It uses `io_orientation(img.affine)` (in the last line) where the `Nifti1Image` is converted to `numpy.ndarray` by `img.affine` before it is sent as an argument to `io_orientation`.

`io_orientation` function is again a function from `nibabel` library :

```
def io_orientation(affine, tol=None):
    """ Orientation of input axes in terms of output axes for `affine`

    Valid for an affine transformation from ``p`` dimensions to ``q``
    dimensions (``affine.shape == (q + 1, p + 1)``).

    The calculated orientations can be used to transform associated
    arrays to best match the output orientations. If ``p`` > ``q``, then
    some of the output axes should be considered dropped in this
    orientation.

    Parameters
    ----------
    affine : (q+1, p+1) ndarray-like
       Transformation affine from ``p`` inputs to ``q`` outputs.  Usually this
       will be a shape (4,4) matrix, transforming 3 inputs to 3 outputs, but
       the code also handles the more general case
    tol : {None, float}, optional
       threshold below which SVD values of the affine are considered zero. If
       `tol` is None, and ``S`` is an array with singular values for `affine`,
       and ``eps`` is the epsilon value for datatype of ``S``, then `tol` set
       to ``S.max() * max((q, p)) * eps``

    Returns
    -------
    orientations : (p, 2) ndarray
       one row per input axis, where the first value in each row is the closest
       corresponding output axis. The second value in each row is 1 if the
       input axis is in the same direction as the corresponding output axis and
       -1 if it is in the opposite direction.  If a row is [np.nan, np.nan],
       which can happen when p > q, then this row should be considered dropped.
    """
    affine = np.asarray(affine)
    q, p = affine.shape[0] - 1, affine.shape[1] - 1
    .
    .
    .
```
The error comes in line 

` q, p = affine.shape[0] - 1, affine.shape[1] - 1
`
Using any other value instead of `q` and `p` seems to be working fine (snapshot below where I use a random varable `v` and `e` --note, we are in debugger mode in the snapshot) but as soon as I execute the same line with `q` and `p`, it beaks:

![image](https://user-images.githubusercontent.com/23316280/130721444-263ce0d4-3a95-4234-911b-ddc05525d1e1.png)

The error is the following:

```
  File "/home/srishtiy/dev/neuropoly/ivadomed/venv-ivadomed/lib/python3.8/site-packages/nibabel/orientations.py", line 58, in io_orientation
    q, p = affine.shape[0] - 1, affine.shape[1] - 1
  File "/home/srishtiy/dev/neuropoly/ivadomed/venv-ivadomed/lib/python3.8/site-packages/nibabel/orientations.py", line 58, in io_orientation
    q, p = affine.shape[0] - 1, affine.shape[1] - 1
  File "/usr/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.8/bdb.py", line 113, in dispatch_line

```

**Comment by jcohenadad** [comment]
about https://github.com/ivadomed/ivadomed/issues/921#issuecomment-905118099: there are files with the mentioned suffix. 

<details><summary>Terminal output</summary>

```console
(venv) julien-macbook:~/data $ ivadomed_download_data -d data_example_spinegeneric
2021-08-25 06:17:06.821 | INFO     | ivadomed.utils:init_ivadomed:410 - 
ivadomed (git-master-49b07e4459a8522ff42351df9f4f3445605930b9)

Trying URL: https://github.com/ivadomed/data_example_spinegeneric/archive/r20200825.zip
Downloading: data_example_spinegeneric-r20200825.zip
Unzip data to: /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/tmpfcgk2wrd
Removing temporary folders...
Folder Created: /Users/julien/data/data_example_spinegeneric
(venv) julien-macbook:~/data $ cd data_example_spinegeneric
(venv) julien-macbook:~/data/data_example_spinegeneric $ ll
total 40
drwxr-xr-x   19 julien  staff   608 25 Aug 06:18 .
drwxr-xr-x  121 julien  staff  3872 25 Aug 06:17 ..
-rw-r--r--    1 julien  staff    64 25 Aug 06:18 .distriploy.yml
-rw-r--r--    1 julien  staff  1252 25 Aug 06:18 README.md
-rw-r--r--    1 julien  staff  2810 25 Aug 06:18 dataset_description.json
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 derivatives
-rw-r--r--    1 julien  staff  1178 25 Aug 06:18 participants.json
-rw-r--r--    1 julien  staff  1729 25 Aug 06:18 participants.tsv
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-cardiff03
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-hamburg01
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-juntendo750w01
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-mpicbs06
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-oxfordFmrib07
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-oxfordFmrib11
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-sapienza05
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-strasbourg04
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-tokyoSkyra06
drwxr-xr-x    3 julien  staff    96 25 Aug 06:18 sub-unf01
drwxr-xr-x    4 julien  staff   128 25 Aug 06:18 trained_model
(venv) julien-macbook:~/data/data_example_spinegeneric $ find . -name "*_csfseg-manual.*"
./derivatives/labels/sub-sapienza05/anat/sub-sapienza05_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-unf01/anat/sub-unf01_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-tokyoSkyra06/anat/sub-tokyoSkyra06_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-juntendo750w01/anat/sub-juntendo750w01_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-oxfordFmrib07/anat/sub-oxfordFmrib07_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-oxfordFmrib11/anat/sub-oxfordFmrib11_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-cardiff03/anat/sub-cardiff03_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-mpicbs06/anat/sub-mpicbs06_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-strasbourg04/anat/sub-strasbourg04_T2w_csfseg-manual.nii.gz
./derivatives/labels/sub-hamburg01/anat/sub-hamburg01_T2w_csfseg-manual.nii.gz
```

</details>

From your post @copperwiring :

![image](https://user-images.githubusercontent.com/2482071/130773586-c9365eae-a0e4-4301-add9-c6f9f59b9ed3.png)

Maybe you didn't find the files because of the type (missing an "s").

**Comment by SpartacusIsBack** [comment]
> There are some minor issues in the documentation of [Cascaded Tutorial](https://ivadomed.org/en/latest/tutorials/cascaded_architecture.html), description of them is mentioned below:
> 
> ### Issue 1:
> In the section of [Configuration File](https://ivadomed.org/en/latest/tutorials/cascaded_architecture.html#configuration-file), it is written,
> 
> `"object_detection_path": "<PATH_TO_DATASET>/data_example_spinegeneric/trained_model/seg_sc_t1-t2-t2s-mt" `
> 
> It should be:
> 
> `"object_detection_path": "<PATH_TO_DATASET>/trained_model/seg_sc_t1-t2-t2s-mt" `
> 
> ### Issue 2:
> Training it using the config file gives error `tupple index out of range`
> 
> ```
> Traceback (most recent call last):
>   File "/home/srishtiy/dev/neuropoly/ivadomed/venv-ivadomed/bin/ivadomed", line 11, in <module>
>     load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
>   File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/main.py", line 566, in run_main
>     run_command(context=context,
>   File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/main.py", line 386, in run_command
>     ds_valid = get_dataset(bids_df, loader_params, valid_lst, transform_valid_params, cuda_available, device,
>   File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/main.py", line 117, in get_dataset
>     ds = imed_loader.load_dataset(bids_df, **{**loader_params, **{'data_list': data_lst,
>   File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/loader/loader.py", line 88, in load_dataset
>     dataset = BidsDataset(bids_df=bids_df,
>   File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/loader/bids_dataset.py", line 91, in __init__
>     bounding_box_dict = imed_obj_detect.load_bounding_boxes(object_detection_params,
>   File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/object_detection/utils.py", line 248, in load_bounding_boxes
>     bounding_box_dict = generate_bounding_box_file(subject_path_list,
>   File "/home/srishtiy/dev/neuropoly/ivadomed/ivadomed/object_detection/utils.py", line 122, in generate_bounding_box_file
>     ras_orientation = nib.as_closest_canonical(object_mask)
>   File "/home/srishtiy/dev/neuropoly/ivadomed/venv-ivadomed/lib/python3.8/site-packages/nibabel/funcs.py", line 205, in as_closest_canonical
>     img = img.as_reoriented(io_orientation(img.affine))
>   File "/home/srishtiy/dev/neuropoly/ivadomed/venv-ivadomed/lib/python3.8/site-packages/nibabel/orientations.py", line 55, in io_orientation
>     q, p = affine.shape[0] - 1, affine.shape[1] - 1
> IndexError: tuple index out of range
> ```
> 
> #### Reproduce issue 2
> Set parameters in the `config` file as recommended in the [tutorial](https://ivadomed.org/en/latest/tutorials/cascaded_architecture.html#) and train using `ivadomed -c config.json `

Thanks for posting this issue. :+1: 
We are having exactly the same issue and cannot figure out a workaround. 

Hence, quite stuck at this point in this very interesting tutorial 
Any suggestion or advice on it would be highly appreciated. Thanks in advance.

**Comment by mariehbourget** [comment]
Hi everyone!
Issue 2 was raised and investigate in issue #775 with a potential fix. If I'm not mistaken, a PR is opened to address it (#758) @dyt811, @cakester?

**Comment by copperwiring** [comment]
@mariehbourget Since the issue was already raise in #775 and is being addressed in #758 , should this issue still remain open?

**Comment by mariehbourget** [comment]
> should this issue still remain open?

I would keep it open until the "issue 1" from your original comment is fixed.

**Comment by copperwiring** [comment]
@mariehbourget Thank you. I have fixed issue 1 here: https://github.com/ivadomed/ivadomed/pull/922. Once this is approved, I'll go ahead an close this if you think it's alright to close it to avoid duplication.
