### ISSUE TITLE
FiLM pipeline doesn't work with "custom" metadata.

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#940]
### Current behavior
The [FiLM metadata option](https://ivadomed.org/en/latest/configuration_file.html#filmedunet) can be set to `contrasts`, `mri_params` or to a "custom" name corresponding to a column of the `participants.tsv` file.

The "custom" option is not working and gives the following error while loading the data:
<details open>
<summary> Error message </summary>

```
Traceback (most recent call last):
  File "/home/mhbourget/venv-ivadomed-38c/bin/ivadomed", line 11, in <module>
    load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
  File "/home/mhbourget/code/ivadomed/ivadomed/main.py", line 567, in run_main
    run_command(context=context,
  File "/home/mhbourget/code/ivadomed/ivadomed/main.py", line 387, in run_command
    ds_valid = get_dataset(bids_df, loader_params, valid_lst, transform_valid_params, cuda_available, device,
  File "/home/mhbourget/code/ivadomed/ivadomed/main.py", line 118, in get_dataset
    ds = imed_loader.load_dataset(bids_df, **{**loader_params, **{'data_list': data_lst,
  File "/home/mhbourget/code/ivadomed/ivadomed/loader/loader.py", line 91, in load_dataset
    dataset = BidsDataset(bids_df=bids_df,
  File "/home/mhbourget/code/ivadomed/ivadomed/loader/bids_dataset.py", line 103, in __init__
    df_sub, roi_filename, target_filename, metadata = self.create_filename_pair(multichannel_subjects, subject,
  File "/home/mhbourget/code/ivadomed/ivadomed/loader/bids_dataset.py", line 208, in create_filename_pair
    self.create_metadata_dict(metadata_choice, df_sub, bids_df)
  File "/home/mhbourget/code/ivadomed/ivadomed/loader/bids_dataset.py", line 150, in create_metadata_dict
    metadata[metadata_choice] = df_sub[metadata_choice].values[0]
NameError: name 'metadata' is not defined
```
</details>

This is because the variable `metadata` is not defined in (or passed to) the [create_metadata_dict](https://github.com/ivadomed/ivadomed/blob/d71a1c4711d03da7c61a473f571134b262684073/ivadomed/loader/bids_dataset.py#L145) function of `bids_dataset.py`.

The error seems to come from a refactoring we did in #765.
I tested with this config file: [config_film.zip](https://github.com/ivadomed/ivadomed/files/7102183/config_film.zip). In that case the custom metadata is `"metadata": "sex"`. Before the refactoring PR (commit ccd82d22) the images are loaded and the training start normally. After the PR (commit ebddbfb and after), the loader returns the error above.

#### Notes
1. the `config_film.json` file I used to test contains the `"NumpyToTensor": {}` transform otherwise it would not work with older commits.
2. At the time of the problematic refactoring, the `create_metadata_dict` was in `loader.py` (and not `bids_dataset.py`).
3. the FiLM pipeline also have known issues with the `contrasts` option under certain circumstances since the integration of the new loader. Details in issue #710, but it should not affect the "custom" metadata option.

**Comment by dyt811** [comment]
Good catch. IDE actually caught this error but during the extraction out of the `load.py`, I think specific function was not reviewed in detail. First thought is let's try to add meta-data past to it and see. We will get a PR going and test it out a bit more.

**Comment by cakester** [comment]
@mariehbourget I have added metadata t the function, how did you test for this?

**Comment by mariehbourget** [comment]
> @mariehbourget I have added metadata to the function, how did you test for this?

I tested with the config file from my initial comment above.

**Comment by cakester** [comment]
> > @mariehbourget I have added metadata to the function, how did you test for this?
> 
> I tested with the config file from my initial comment above.

what command do you run?

**Comment by mariehbourget** [comment]
> what command do you run?

The command line tool:
`ivadomed -c <path_to_config_file>`

**Comment by dyt811** [comment]
@cakester you will need `data_example_spinegeneric` data from https://ivadomed.org/en/latest/tutorials/one_class_segmentation_2d_unet.html 
![image](https://user-images.githubusercontent.com/6720068/135100147-e61d6274-d001-429d-a23b-fd7e997dac50.png)
