### ISSUE TITLE
`GeneralizedDiceLoss` fails with batch_size > 1 when `include_background=true`.

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#960]
### Current behavior
The following error happens when trying to use `GeneralizedDiceLoss` with a `batch_size > 1` and `include_background=true`.

<details>
<summary> Error message </summary>

```
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/maboudb/venv-ivadomed-38c/bin/ivadomed", line 33, in <module>
    sys.exit(load_entry_point('ivadomed', 'console_scripts', 'ivadomed')())
  File "/home/GRAMES.POLYMTL.CA/maboudb/ivadomed/ivadomed/main.py", line 567, in run_main
    run_command(context=context,
  File "/home/GRAMES.POLYMTL.CA/maboudb/ivadomed/ivadomed/main.py", line 408, in run_command
    best_training_dice, best_training_loss, best_validation_dice, best_validation_loss = imed_training.train(
  File "/home/GRAMES.POLYMTL.CA/maboudb/ivadomed/ivadomed/training.py", line 181, in train
    loss = loss_fct(preds, gt_samples)
  File "/home/GRAMES.POLYMTL.CA/maboudb/venv-ivadomed-38c/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/maboudb/ivadomed/ivadomed/losses.py", line 201, in forward
    input_background[input.sum(1).expand_as(input_background) == 0] = 1
RuntimeError: The expanded size of the tensor (1) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [4, 1, 256, 256].  Tensor sizes: [4, 256, 256]
```
</details>

According to [this](https://discuss.pytorch.org/t/runtimeerror-the-expanded-size-of-the-tensor-must-match-the-existing-size/105523), it seems to be because `expand_as` cannot be used with a non-singleton dimension (batch size), like it is done here:
https://github.com/ivadomed/ivadomed/blob/ac29c7cbe299e6478854823ed6bd818c0e5f9642/ivadomed/losses.py#L200-L202
In my case `batch_size = 4` and `patch_size = 256x256`, so `[4, 256, 256]` cannot be expand to `[4, 1, 256, 256]`

### Expected behavior
I found a work-around which is to create new tensors, replacing the lines above with:
```
# fill with opposite
input_sum = input.sum(1)[:, None, :, :]
input_background[input_sum == 0] = 1
target_sum = target.sum(1)[:, None, :, :]
target_background[target_sum == 0] = 1
```
It works but may be less efficient because of the new allocation of memory for the new tensors.

Is there a better way to work around this issue?
I want to use the same "include background" feature in the implementation of `CrossEntropyLoss` and would rather harmonize with `GeneralizedDiceLoss`.

Please let me know if you have more insights on this. Thanks!

**Comment by charleygros** [comment]
Great stuffs @mariehbourget , as always.

I'm surprised by this error: did not occur before.

Your workaround looks good to me.

Efficiency / Optimisation: maybe @dyt811 may know?
