### ISSUE TITLE
Unable to train using ivadomed because of a UnicodeDecodeError

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/ivadomed#981]
## Issue description
Unable to train a 2D segmentation model due to a UnicodeDecodeError occuring outside the scope of ivadomed. 

### Current behavior

I am trying to traing a model on a BIDSified dataset but am encountering a decoding error, in particular - `UnicodeDecodeError 'utf-8' codec can't decode byte 0xc4 in position 1430: invalid continuation byte`. This is due to some non-ascii character in one of the json files, which is being flagged as an error while the indexing is done. I ran the debugger in order to pinpoint the source but since this due to some decoding error, the debugger's final reach is until [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataframe.py#L110) in `loader/bids_dataframe.py`. This initially suggested that some parameters of BIDSLayout can be tweaked to avoid this error.

### Things already tried
@mariehbourget suggested to consider looking at this independently without involving ivadomed by loading the files using the json package directly. I wrote a script to do this, and I found that there are 74 json files which are flagged as erroneous. However, each json file has ~1800 lines and I do not see any way to look through all those lines to find some single non-ascii character.

@jcohenadad Our hunch about using `validate=False` (which is by default True) in the `pybids.BIDSLayout`'s function call (see the line's link above) did not work as I got the same error. I also added `validate=False` in [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataframe.py#L105) for the indexer, but still no luck.

Since I will only be using the `.nii.gz` files, I thought that this error could be prevented if we don't index any metadata in the first place. Therefore, I tried adding the argument `index_metadata=False` (which was set to `True` by default in [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataframe.py#L105) for the [BIDS layout indexer class](https://github.com/bids-standard/pybids/blob/master/bids/layout/index.py#L43). Now I am getting this error - `TypeError cannot unpack non-iterable NoneType object` (possibly because "metadata" is now `None` and it cannot be returned). Therefore, it seems that indexing the metadata is crucial for other ivadomed functionalities, and I cannot simply not index the metadata without breaking other function calls. 

I am wondering whether there is any way to not index the metadata (json) files and load simply the `.nii.gz` files for training? Any suggestions are highly appreciated! 
(tagging @charleygros @andreanne-lemay in case they have experienced anything like this?)

<details>
<summary> Full error trace of the UnicodeDecodeError </summary>

```
Traceback (most recent call last):
  File "ivadomed/ivadomed/main.py", line 574, in <module>
    run_main()
  File "ivadomed/ivadomed/main.py", line 567, in run_main
    run_command(context=context,
  File "ivadomed/ivadomed/main.py", line 352, in run_command
    bids_df = BidsDataframe(loader_params, path_output, derivatives=True)
  File "/home/nagakarthik/deepLearning/ivadomed_experiments/ivadomed/ivadomed/loader/bids_dataframe.py", line 65, in __init__
    self.create_bids_dataframe()
  File "/home/nagakarthik/deepLearning/ivadomed_experiments/ivadomed/ivadomed/loader/bids_dataframe.py", line 115, in create_bids_dataframe
    layout = pybids.BIDSLayout(str(path_data), config=self.bids_config, indexer=indexer,
  File "/home/nagakarthik/deepLearning/venvDL/lib/python3.8/site-packages/bids/layout/layout.py", line 156, in __init__
    indexer(self)
  File "/home/nagakarthik/deepLearning/venvDL/lib/python3.8/site-packages/bids/layout/index.py", line 112, in __call__
    self._index_metadata()
  File "/home/nagakarthik/deepLearning/venvDL/lib/python3.8/site-packages/bids/layout/index.py", line 380, in _index_metadata
    file_md.update(pl())
  File "/home/nagakarthik/deepLearning/venvDL/lib/python3.8/site-packages/bids/layout/index.py", line 275, in load_json
    return json.load(handle)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1430: invalid continuation byte
```

</details>

<details>
<summary> Error trace when <code> index_metadata=False </code> </summary>

```
  File "/home/nagakarthik/deepLearning/ivadomed_experiments/ivadomed/ivadomed/loader/bids_dataset.py", line 103, in __init__
    df_sub, roi_filename, target_filename, metadata = self.create_filename_pair(multichannel_subjects, subject,
  File "/home/nagakarthik/deepLearning/ivadomed_experiments/ivadomed/ivadomed/loader/loader.py", line 91, in load_dataset
    dataset = BidsDataset(bids_df=bids_df,
  File "/home/nagakarthik/deepLearning/ivadomed_experiments/ivadomed/ivadomed/main.py", line 118, in get_dataset
    ds = imed_loader.load_dataset(bids_df, **{**loader_params, **{'data_list': data_lst,
  File "/home/nagakarthik/deepLearning/ivadomed_experiments/ivadomed/ivadomed/main.py", line 387, in run_command
    ds_valid = get_dataset(bids_df, loader_params, valid_lst, transform_valid_params, cuda_available, device,
  File "/home/nagakarthik/deepLearning/ivadomed_experiments/ivadomed/ivadomed/main.py", line 567, in run_main
    run_command(context=context,
  File "/home/nagakarthik/deepLearning/ivadomed_experiments/ivadomed/ivadomed/main.py", line 574, in <module> (Current frame)
    run_main()

```

</details>

**Comment by mariehbourget** [comment]
Hi @naga-karthik, here are a few thoughts about your issue.

> Since I will only be using the `.nii.gz` files, I thought that this error could be prevented if we don't index any metadata in the first place. Therefore, I tried adding the argument `index_metadata=False` (which was set to `True` by default in [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataframe.py#L105) for the [BIDS layout indexer class](https://github.com/bids-standard/pybids/blob/master/bids/layout/index.py#L43). Now I am getting this error - `TypeError cannot unpack non-iterable NoneType object` (possibly because "metadata" is now `None` and it cannot be returned). Therefore, it seems that indexing the metadata is crucial for other ivadomed functionalities, and I cannot simply not index the metadata without breaking other function calls.

I think this is the right fix. As far as I know, this metadata should not ne crucial for other ivadomed functionalities, unless you use the metadata for training (ex: with FilM). Can you share your config file?

I was unable to reproduce the error:
1) I tried `index_metadata=False`  on `data_spinegeneric_example` with `ivadomed/config/config.json` config file, the training starts without error, and the `bids_dataframe.csv` in the output folder does not contain the json metadata (as expected).
2) I also tried deleting all the json file from the dataset (except `participants.json` and `dataset_description.json`) and the training also starts normally.

**Comment by dyt811** [comment]
Sorry, just a really random tangential thought, could this be related to CRLF vs LF error? As they can be sometimes related to UnicodeDecodeError? Do you know if all the files are were originally generated on the same OS type as what you are trying to run the analyses on?

**Comment by naga-karthik** [comment]
Thank you @mariehbourget for your effort in the follow-up! I have a few questions: 

1. When you say you tried `index_metadata=False`, you mean that you changed that particular argument in [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataframe.py#L105), right? Or, did you add an additional key-value parameter in your `ivadomed/config/config.json` file? I have not tried the latter but when changed that argument manually, it gave another error (already mentioned above) in [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataset.py#L103).
2. This looks like a great idea, thank you for this! I'll try this myself and see if it works on my dataset.

Also, if it helps, here's my config file below:
<details> 

<summary> Config file </summary>

```
{
    "command": "train",
    "gpu_ids": [0],
    "path_output": "sciLesions_exp1",
    "model_name": "unet2d_singleContrast",
    "debugging": false,
    "object_detection_params": {
        "object_detection_path": null,
        "safety_factor": [1.0, 1.0, 1.0]
    },
    "loader_parameters": {
        "path_data": ["./datasets/sci-zurich_full"],
        "subject_selection": {"n": [], "metadata": [], "value": []},
        "target_suffix": ["_lesion-manual"],
        "extensions": [".nii.gz"],
        "roi_params": {
            "suffix": null,
            "slice_filter_roi": null
        },
        "contrast_params": {
            "training_validation": ["T2w"],
            "testing": ["T2w"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": true
        },
        "slice_axis": "sagittal",
        "multichannel": false,
        "soft_gt": false
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 42,
        "split_method" : "participant_id",
        "data_testing": {"data_type": null, "data_value":[]},
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.2
    },
    "training_parameters": {
        "batch_size": 32,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 10,
            "early_stopping_patience": 5,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 0.001,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-2
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.1,
        "final_activation": "sigmoid",
        "depth": 4
    },
    "FiLMedUnet": {
        "applied": false,
        "metadata": "contrasts",
        "film_layers": [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    },
    "Modified3DUNet": {
        "applied": false,
        "length_3D": [128, 128, 16],
        "stride_3D": [128, 128, 16],
        "attention": false,
        "n_filters": 8
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {
        "remove_noise": {"thr": -1},
        "keep_largest": {},
        "binarize_prediction": {"thr": 0.5},
        "uncertainty": {"thr": -1, "suffix": "_unc-vox.nii.gz"},
        "fill_holes": {},
        "remove_small": {"unit": "vox", "thr": 3}
    },
    "evaluation_parameters": {
        "target_size": {"unit": "vox", "thr": [20, 100]},
        "overlap": {"unit": "vox", "thr": 3}
    },
    "transformation": {
        "Resample":
        {
            "wspace": 0.75,
            "hspace": 0.75,
            "dspace": 1
        },
        "CenterCrop": {
            "size": [256, 256]},
        "RandomAffine": {
            "degrees": 5,
            "scale": [0.1, 0.1],
            "translate": [0.03, 0.03],
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "ElasticTransform": {
			"alpha_range": [28.0, 30.0],
			"sigma_range":  [3.5, 4.5],
			"p": 0.1,
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
      "NumpyToTensor": {},
      "NormalizeInstance": {"applied_to": ["im"]}
    }
}

```
</details>
 
@dyt811 I am unaware of what that error is. Would you have any reference link to where this happened before? To answer your question, the dataset I am using is from Zurich, so the generation of the files and training are definitely on different systems.

**Comment by dyt811** [comment]
This is a good resources: https://blog.codinghorror.com/the-great-newline-schism/

Namely any files generated on windows and opened on linux or the reverse may present this problem when not obtained through git (git checkin/out takes care of this in the background).

**Comment by mariehbourget** [comment]
Thanks for the config file, I don't see anything that would require metadata.

> 1. When you say you tried `index_metadata=False`, you mean that you changed that particular argument in [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataframe.py#L105), right? Or, did you add an additional key-value parameter in your `ivadomed/config/config.json` file? I have not tried the latter but when changed that argument manually, it gave another error (already mentioned above) in [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataset.py#L103).

I tried the same as you, adding `index_metadata=False` in [this line](https://github.com/ivadomed/ivadomed/blob/2e5f70faa67e2a21f9ae11ada69145256aa6629b/ivadomed/loader/bids_dataframe.py#L105), and it worked for me.
So the `TypeError cannot unpack non-iterable NoneType object` may not be related to the metadata itself.
