### ISSUE TITLE
The dataframe generation takes along time

### ISSUE THREAD

**Issue by MosyMosy** [ivadomed/ivadomed#986]
## Issue description
When we want to train a model on a large-scale dataset (cem500k) the data frame generation takes a long time (having no idea if finish at all). 
### Current behavior

These are  the last log message I get:

> 2021-11-08 16:01:42.007 | INFO     | ivadomed.config_manager:_display_differing_keys:150 - Adding the following keys to the configuration file
> 2021-11-08 16:01:42.007 | INFO     | ivadomed.config_manager:deep_dict_compare:43 -     lr_scheduler: base_lr: 1e-05
> 2021-11-08 16:01:42.007 | INFO     | ivadomed.config_manager:deep_dict_compare:43 -     lr_scheduler: max_lr: 0.01
> 2021-11-08 16:01:42.007 | INFO     | ivadomed.config_manager:_display_differing_keys:152 -
> 
> 2021-11-08 16:01:42.007 | INFO     | ivadomed.utils:get_command:356 - No CLI argument given for command: ( --train | --test | --segment ). Will check config file for command...
> 2021-11-08 16:01:42.007 | INFO     | ivadomed.utils:get_path_output:371 - CLI flag --path-output not used to specify output directory. Will check config file for directory...
> 2021-11-08 16:01:42.007 | INFO     | ivadomed.utils:get_path_data:383 - CLI flag --path-data not used to specify BIDS data directory. Will check config file for directory...
> 2021-11-08 16:01:42.008 | INFO     | __main__:set_output_path:198 - Output path already exists: out_cem500k_BIDS
> 2021-11-08 16:01:42.570 | INFO     | ivadomed.utils:define_device:135 - Using GPU ID 0
> 2021-11-08 16:01:42.570 | INFO     | ivadomed.utils:display_selected_model_spec:145 - Selected architecture: Unet, with the following parameters:
> 2021-11-08 16:01:42.571 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   dropout_rate: 0.2
> 2021-11-08 16:01:42.571 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   bn_momentum: 0.1
> 2021-11-08 16:01:42.571 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   depth: 4
> 2021-11-08 16:01:42.571 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   is_2d: True
> 2021-11-08 16:01:42.571 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   final_activation: sigmoid
> 2021-11-08 16:01:42.571 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   length_2D: [256, 256]
> 2021-11-08 16:01:42.571 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   stride_2D: [244, 244]
> 2021-11-08 16:01:42.571 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   folder_name: cem500k_BIDS
> 2021-11-08 16:01:42.572 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   in_channel: 1
> 2021-11-08 16:01:42.572 | INFO     | ivadomed.utils:display_selected_model_spec:148 -   out_channel: 3

### Expected behavior
 
I think after some reasonable time of the data frame preparation, it should go to the dataset loading and data augmentation.

### Steps to reproduce

You can reproduce the whole experiment using [this bash file](https://github.com/MosyMosy/ivadomed/blob/master/jobs/cem500_identity_unet.sh):

in summary, 

1. extract the [cme500k dataset](https://www.ebi.ac.uk/empiar/EMPIAR-10592/) (on the Ivadomed root is a good place).
2. run the [raw_to_BIDS.py](https://github.com/MosyMosy/ivadomed/blob/master/lab/raw_to_BIDS.py) scripts to generate the BIDS-like structured cem500k dataset with 3 targets (2 classes)
3. Train using this [config file](https://github.com/MosyMosy/ivadomed/blob/master/ivadomed/config/config_cem500k_BIDS.json).

### System description

Windows workstation with WSL and Linux ComputeCanada node (186G or 191000M	2 x Intel Gold 6148 Skylake @ 2.4 GHz	1 x NVMe SSD 1.6T	4 x NVidia V100SXM2 (16G memory), connected via NVLink)

### Installed packages

Exactly as described on the installation documents

absl-py==0.15.0
autopep8==1.6.0
backports.lzma==0.0.14
bids-validator==1.8.4
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.7
click==8.0.3
csv-diff==1.1
cycler==0.11.0
dictdiffer==0.9.0
docopt==0.6.2
future==0.18.2
google-auth==2.3.2
google-auth-oauthlib==0.4.6
grpcio==1.41.1
h5py==2.10.0
idna==3.3
imageio==2.10.1
-e git+https://github.com/MosyMosy/ivadomed.git@73f13caa7c3df79cf39c2009524caa234a7ee2ea#egg=ivadomed
joblib==1.1.0
kiwisolver==1.3.2
loguru==0.5.3
Markdown==3.3.4
matplotlib==3.4.3
networkx==2.6.3
nibabel==3.2.1
num2words==0.5.10
numpy==1.21.3
oauthlib==3.1.1
onnxruntime==1.7.0
packaging==21.2
pandas==1.3.4
patsy==0.5.2
Pillow==8.4.0
protobuf==3.19.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybids==0.13.2
pycodestyle==2.8.0
pyparsing==2.4.7
python-dateutil==2.8.2
pytz==2021.3
PyWavelets==1.1.1
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-image==0.18.3
scikit-learn==1.0.1
scipy==1.7.1
seaborn==0.11.2
six==1.16.0
SQLAlchemy==1.3.24
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
threadpoolctl==3.0.0
tifffile==2021.10.12
toml==0.10.2
torch==1.5.0+cpu
torchaudio==0.10.0
torchvision==0.6.0+cpu
tqdm==4.62.3
typing-extensions==3.10.0.2
urllib3==1.26.7
Werkzeug==2.0.2

<details open>
<summary> Output of <code>pip freeze</code> </summary>

```

```

</details>

**Comment by mariehbourget** [comment]
Thank you @MosyMosy for sharing the code and files. We never tried running the dataframe on such a large dataset!

If I understand correctly, after 24h, the command is still running and the `bids_dataframe.csv` file is still not in the `path_output`, correct?

As a first step, would you be able to also share a few images (~5) from the original cme500k dataset so I could reproduce your pipeline without downloading the whole 16 Gig?

I'll try to take a look at the data and config file tomorrow.

**Comment by MosyMosy** [comment]
Hi @mariehbourget, Thanks for your consideration. 
Yes, so it is going to be 40 hours by now. I am suspicious of the "bids_dataframe.py" line 110.

It is simply a directory containing some images without any structure and metadata. [you can download this sample](https://drive.google.com/file/d/1NuHPKaiaXdXTvmgueaxQyH0xZvl85-2d/view?usp=sharing).

Thank you.

**Comment by MosyMosy** [comment]
After 45 hours of running on the aforementioned system and settings, I got this error:

```
Traceback (most recent call last):
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ivadomed/main.py", line 574, in <module>
    run_main()
  File "ivadomed/main.py", line 570, in run_main
    resume_training=bool(args.resume_training))
  File "ivadomed/main.py", line 352, in run_command
    bids_df = BidsDataframe(loader_params, path_output, derivatives=True)
  File "/lustre07/scratch/mosymosy/ivadomed/ivadomed/loader/bids_dataframe.py", line 64, in __init__
    self.create_bids_dataframe()
  File "/lustre07/scratch/mosymosy/ivadomed/ivadomed/loader/bids_dataframe.py", line 115, in create_bids_dataframe
    df_next = layout.to_df(metadata=True)
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/bids/layout/layout.py", line 518, in to_df
    tags = query.all()
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/mosymosy/venv-ivadomed/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) too many SQL variables
[SQL: SELECT tags.file_path AS tags_file_path, tags.entity_name AS tags_entity_name, tags._value AS tags__value, tags._dtype AS tags__dtype
FROM tags
WHERE tags.file_path IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,>
[parameters: ('/localscratch/mosymosy.183615.0/ivadomed/cem500k_BIDS/dataset_description.json', '/localscratch/mosymosy.183615.0/ivadomed/cem500k_BIDS/derivatives/dataset_description.json', '/localscra>
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by mariehbourget** [comment]
Hi @MosyMosy, thank you for the sample dataset.
I was able to reproduce your pipeline on my side and start the training without errors (with only 5 subjects).

This may be a little bit complex to debug because the error is not directly in ivadomed. The error you got above comes from `sqlalchemy` which is a dependency or `pybids` that `ivadomed` uses to index the files in the dataset and create the dataframe. To reduce the numbers of variables, you can:
1) Remove `participants.tsv`, `participants.json`, `samples.tsv` and `samples.json` from your dataset (they are not required if you don't need the metadata from them).
2) In the sidecar json file of each image file (from `sample_metadata.json`), you can remove everything except the `"PixelSize"` field.

I don't know if that would be enough to fix the error and speed-up the process though. I would also recommend to try and load much smaller datasets and increase progressively the size to see what happens. Once the dataframe is created, you may ran into other issues with such a large dataset (see this [issue](https://github.com/ivadomed/ivadomed/issues/799) for example).

There are a few other things that I saw but that are probably unrelated to you issue:
1) In BIDS, the `<label>` following an entity in the filename (ex: `sample-<label>`) must be alphanumeric only. So a name like `sample-0AO4EJXNKJLS_0_0124_0_448` is not good because of the underscores. In the dataframe, the `sample_id` will be cut after the first underscore. Currently, it is working because we force `pybids` to index microscopy files, but it won't in the future (when microscopy is officially included in BIDS).
2) Are the files all `.tiff`? If yes, I would recommend renaming to `.tif` (one f) to follow BIDS and to only use `.tif` in the `extensions` field in the config file.
3) You are using a `PixelSize : [1, 1]` (in um) in the `sample_metadata.json` file, is it the real resolution of the images? With the `Resample : [0.0001, 0.0001]` (in mm) in the config file, it means that after the dataframe is created, every image will be resampled from a resolution of 1um/pixel to a resolution of 0.1 um/pixel before training start. (It may be intentional as 0.1 um/pixel is our current resolution for SEM, but I thought I should mention it.)

**Comment by MosyMosy** [comment]
Hi, I removed all the extra metadata as you said, and the problem still remains with exactly the same output:

> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) too many SQL variables
> [SQL: SELECT tags.file_path AS tags_file_path, tags.entity_name AS tags_entity_name, tags._value AS tags__value, tags._dtype AS tags__dtype
> FROM tags
> WHERE tags.file_path IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, >
> [parameters: ('/localscratch/mosymosy.27641202.0/ivadomed/dataset/cem500k_BIDS/dataset_description.json', '/localscratch/mosymosy.27641202.0/ivadomed/dataset/cem500k_BIDS/deri>
> (Background on this error at: http://sqlalche.me/e/13/e3q8)

I will go with the progressive size increment and I will report the result as soon as possible.
